### ISSUE TITLE
Non-Computed Getters

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx-state-tree#104]
Is it possible to have non-computed getters? Since `mobx` memoizes stuff in computed functions it can sometimes mess things up if they rely on external state or have side effects.

```js
class Example {
  // not computed
  get date() {
    return Date.now();
  }
}

const Example = types.model("Example", {
  // becomes computed
  get date() {
    return Date.now()
  }
})
```

Is there a workaround to avoid this becoming computed in `mobx-state-tree`?

**Comment by mattiamanzati** [comment]
Its not fully true, mobx memoizes only if value is observed. https://github.com/mobxjs/mobx/issues/718 It may be that in mobx-state-tree due to internal observe that value became memoized. Btw, you can use a normal function.

**Comment by mjewell** [comment]
Here's an example of it where it being computed is incorrect inside an observer component: https://codesandbox.io/s/El7o78BZv (if you get the error "Error: Cannot find module "base64-js"" just make a minimal edit to the file, like adding a space, and it will rebuild)

Using a normal function is an ok option but sometimes it is preferable to have it represented as a getter.

**Comment by mweststrate** [comment]
@mjewell the example presented is not entirely correct; computed properties should be pure with respect to the data used and yours isn't. 

The goal of MST is not to provide the full flexibility one has with classes; with all the different kind of attributes, statics, inheritance etc. The goal is to provide a minimal subset of that which is sufficient for day to day usage and presents only one way of doing things. In your example case that is: use a function instead of a computed property.
