### ISSUE TITLE
Actions not created (and therefore afterCreate never called) unless property referenced.

### ISSUE THREAD

**Issue by lucsky** [mobxjs/mobx-state-tree#1089]
**_Bug report_**

* [X] I've checked documentation and searched for existing issues
* [X] I've made sure my project is based on the latest MST version
* [X] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/kwqkq0o587

**Describe the expected behavior**
In the provided sandbox snippet I would expect `DEFINING ACTIONS` and `AFTER CREATE` to show up as the `Store` model is being instantiated.

**Describe the observed behavior**
Only 'STORE CREATED' shows up in the console, the `actions` factory is not called and `afterCreate` is therefore not called either.

However, if you _reference_ one of the root property, everything works as expected.

**Comment by luisherranz** [comment]
That's part of MST design. `store.foo` is not really created until some part of your app access it:
https://codesandbox.io/s/jnr55nmr1w

That way it avoids initializaing not used observables.

**Comment by luisherranz** [comment]
What's your use case? There is a discussion going on right now about a new API for `effects`:
https://github.com/mobxjs/mobx-state-tree/issues/867

**Comment by mikepulaski** [comment]
@luisherranz Hi! @lucsky and I are on the same team. I originally discovered this behavior for a component within our app.

We have a remote notification model that needs to register itself to an API, immediately, when the code is loaded. There may not be an additional component observing this model when the code is loaded (for the first couple of seconds, perhaps) because we essentially have a wait condition to make sure a valid session is established before displaying notifications that may require a user to be authenticated.

It is possible for us to rewrite our reactions so that the notification model's properties are referenced, although the reasoning for expressing our reactions in such a way may not be as clear.

This is certainly an edge case, though, and we can just add a few comments in our code 😄

**Comment by luisherranz** [comment]
Could you please check https://github.com/mobxjs/mobx-state-tree/issues/867 and see if using something like the `.effects()` API proposed there would fit your use case? For context, `effects` would be a way to run things like reactions and they should be launched even if the node it's not observed.
