### ISSUE TITLE
v3.9.0 Regression: Optional Types on model and Mode.create() bug

### ISSUE THREAD

**Issue by jadbox** [mobxjs/mobx-state-tree#1102]
In mobx-state-tree@3.9.0, it seems like `types.optional(types.frozen())` for a model attribute will trigger a type to require a value during Mode.create() construction, meaning you have to provide a value (like null) for that exact field.

See:
https://github.com/alisd23/mst-react-router/issues/16

**Comment by xaviergonz** [comment]
I just tried this
```
    const I = types.optional(types.frozen<number>(), 6)
    I.create()
    I.create(7)
```

and it compiles.

Btw, in store.js
`location: types.optional(types.frozen())`, is missing the second argument (the default value) unless it is supposed to be undefined.

Also as for the type definition it should be (since it is optional)
`location: IOptionalType<IType<Location, Location, Location>>;`

**Comment by xaviergonz** [comment]
that's actually why an empty argument is not working, because that type is not marked as optional, therefore TS thinks the create method must have it included

**Comment by xaviergonz** [comment]
if you change the type definition to that does it work ok?

**Comment by jadbox** [comment]
I'm not the author, but I'll close this issue for now until I get validation.

**Comment by belozer** [comment]
@jadbox mybe need use
`types.maybe(types.frozen())` or `types.maybeNull(types.frozen())`
