### ISSUE TITLE
onAction not trigger in componentDidMount

### ISSUE THREAD

**Issue by aMahdaoui** [mobxjs/mobx-state-tree#1119]
**_Question_**

* [ ] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I tried to use onAction in componentDidMount, seems it's not works until i fill the input Text Field, but when i use it on the constructor it works fine directly:
```javascript 
componentDidMount() {    
      onAction (getRoot(this.props.widget), (call ) => {    
         if (call.name === "changeVarValue") {    
              console.log('change var value invoked take care of it', call.args[0]);     
              // other code here     
         }    
     });     
}
```
Thanks

**Comment by aMahdaoui** [comment]
I have a made a demo on codesandbox that illustrate this case : 
[https://codesandbox.io/s/n51wplxzp](url) 
on index.js : 
if widget value is not null, setVariable1 action is called in constructor(), 
Thank you;

**Comment by xaviergonz** [comment]
that's because on action is called for actions that happen after the call
in your case:
- input widget constructor - nothing
- js widget constructor - nothing
- input widget mounts - componentDidMount - does the action (nobody is listening to it yet)
- js widget mounts - componentDidMount - now it is listening to actions, but the action already happened

by putting it in the js widget constructor the following happens
- input widget constructor
- js widget constructor - start listening for actions
- input widget mounts - action is performed and listened by the previos hook
- js widget mounts - nothing

**Comment by aMahdaoui** [comment]
Thanks @xaviergonz  for your response, 
In fact i just let action listner in the constructor, as you explain, but when a try to fetch data from an API by using **_axios_** with **_flow/yield_** methode (**fetchData ()** ) it not works again 

here are an update codeSandbox link : [https://codesandbox.io/s/404p48l67](url)

**Comment by aMahdaoui** [comment]
I found this wonderful sentence on MST docs 

> on Patch events are emitted immediately and will not await the end of a transaction. Patches can be **_used to deep observe a model tree_**.

So i replace onAction by onPatch and it works very well 

But using onPatch i can't have access to args and the name of the action that fire the patch.
there is a chance to get these kind of informations ? 

Thanks
