### ISSUE TITLE
onBecomeObserved doesn't get triggered

### ISSUE THREAD

**Issue by giggo1604** [mobxjs/mobx-state-tree#1180]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/8p3jvnpp9) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
[![Edit mst onBecomeObserved](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8p3jvnpp9)

**Describe the expected behavior**
The console should print out `Hello World!` because the counter property gets observed. A similar example with mobx (comment) works

**Describe the observed behavior**
The console does't print out `Hello World!` even tough the counter property gets observed. Therefore onBecomeObserved does not work properly with mobx-state-tree.

This code snipped has been taken from https://github.com/mobxjs/mobx-state-tree/issues/987 which might be outdated and there is already a way how to get this to work.

Any help on this issue would be appreciated :)

**Comment by xaviergonz** [comment]
@mweststrate any idea?

**Comment by mweststrate** [comment]
The reason that it doesn't work, is because in MST all fields are observed by default (to keep the snapshots hot). So they are already observed before `afterCreate` is called, hence the hook never fires. The hook will fire if you set up the hook in the initialization block ([example](https://codesandbox.io/s/92nv0nm6kr)), but it is in principle pointless, as long as the node is alive, all it's fields will be observed.

What were you trying to achieve @giggo1604 ?

**Comment by giggo1604** [comment]
Okay this makes sense to me. I'm trying to fetch some data when it is actually needed and tried to solve it that was instead of calling it on componentDidMount, which might not optimal if the same data is required in different components.

**Comment by mweststrate** [comment]
Make a function on the on the model that fetches it, and create a private
flag to track whether you are already fetching should do it. That will in
any case be easier to follow, even if this worked :)

**Comment by giggo1604** [comment]
@mweststrate thanks for your time and effort, this sounds like the right approch to me.

**Comment by ImBrek** [comment]
Hi. I have a same problem. But I want to use onBecomeObserved to update a model field by websockets. The main problem is that websocket subscription is very heavy and I should make subscription only for visible models, and teardown subscription when user goes out. Is there any workaround to do it?

**Comment by Maaartinus** [comment]
@ImBrek I'm having a very similar problem (with polling instead of websockets, i.e., even more heavy) and I'm unsure if some magic would be better than a manual solution. Unless we get a better recommendation, I'll use my `useObserving(listOfModels)` hook. It's needed usually just once per page, so no big deal. Maybe a usable workaround for you?
