### ISSUE TITLE
Having to use setTimeout to test mocked functions when declaring actions in two steps/using helper functions

### ISSUE THREAD

**Issue by Peterabsolon** [mobxjs/mobx-state-tree#1191]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/nn8jpn07p4

**Describe the expected behavior**
No matter how the actions are defined the model should be ...the same?

**Describe the observed behavior**
I'm using Typescript and I want to reuse actions inside a block. I hence need to either use helper functions or declare them in two steps. The default style when the actions are returned directly doesn't work with Typescript because it will complain that I cannot use a method returned in a block I'm currently in.

So I'm using the other two methods and they work as they should. All good.

This issue comes when writing tests. The default style work, I can replace an action with jest.fn() and assert it has been called when I call another action that uses it.

But when I define my actions in two steps or use helper functions, Jest reports that the function has NOT been called. This is weird because when I console log the action before and after replacing it with a mock, I see it has been replaced. The only thing that helps in this case is to use setTimeout with 0.

I've been trying to understand why this is the case and my only conclusion is that MST does some inner operations when something is overwritten in the tree from outside (I'm using unprotect(store)) that results with the tree not being updated immediately. Because from the language point of view all three methods yield the same result.

Is that the case? Can any of you point me in the right direction? Thanks!

**Comment by xaviergonz** [comment]
> 'm using Typescript and I want to reuse actions inside a block. I hence need to either use helper functions or declare them in two steps

Did you try using `this` when invoking actions or views declared in the same block?

**Comment by Peterabsolon** [comment]
@xaviergonz So that's a neat workaround but it stills fails without setTimeout

**Comment by xaviergonz** [comment]
That's because of this
```
const actions = {
      openModal() {
        console.log("open modal...");
      },
      doStuff() {
        actions.openModal(); // this points to a bound actions.openModal
      }
    };

// then, upton create mst internally will do something like
const storeActions = {...actions} // store.openModal is now a copy of actions.openModal
store.openModal = jest.fn(); // the copy is being mocked
store.doStuff() // but store.doStuff is calling the original (actions.openModal), not the copy
```

as for why it works in setTimeout, it actually doesn't work, but you forgot that for jest to work in async mode you need to either use async and await a promise that resolves the timeout or use a done callback

https://jestjs.io/docs/en/asynchronous

so those "work" because the expect is actually never being called (but actually they fail as well)

**Comment by mweststrate** [comment]
@Peterabsolon Instead of taking the internal shortcut, I think you can use the public api instead? So, use `self.openModel` instead, otherwise you are trying to stub a variable that just lives in a closure, which is not really possible without weird tricks (e.g. pass a param to `openModel`). 

If that doesn't satisfy typescript, there are two things you could do:
1. upcast `self`; correct semantics is first prio, satisfying the static typechecker second. Not all problems in the world can be verified statically :)
2. if there is no other shared state in the closure, you can also just declare two action blocks, as the result of the first one will determine the type of `self` in the second one: `types.model(...).actions(() => ({ openModel() { ... } })).actions(self => { /* self.openModel is known here! */ })`

**Comment by Peterabsolon** [comment]
@mweststrate Yeah using `self.openModal` will result in typescript complaining. Can you elaborate on 1.? I don't understand what you mean by upcasting `self`.

The 2) is an option I used previously until I realized there is a better way (using this or two steps). I disliked it because it forced me to write code in a specific way. So I'd like to avoid that if possible

**Comment by mweststrate** [comment]
(self as any).openModel

Op ma 25 feb. 2019 20:54 schreef Peter Absolon <notifications@github.com>:
