### ISSUE TITLE
Mobx-state-tree Clone also changes the original item?

### ISSUE THREAD

**Issue by edbras** [mobxjs/mobx-state-tree#1215]
Might this be a bug? See: [LINK](https://stackoverflow.com/questions/55088756/mobx-state-tree-clone-also-changes-the-original-item)
I think I do the same as I find the documentation and the movie tutorials on egghead.

**Comment by xaviergonz** [comment]
Nope, you are saving a reference, which points to a given node with a given id
since you are cloning the node and it keeps the same id the reference will keep pointing to the same node

node = some node with id 123, it is on the store tree (let's call this A)
...
originalNode = node // point to some node in the tree with id 123 (points to A)
node = clone(node) 
// A is cloned as B with id 123
// A is removed from tree (originalNode points to nothing since there is no node on the tree with id 123 now)
// B is added to the tree (originalNode points to B since that's the node on the tree with id 123 now)

**Comment by xaviergonz** [comment]
Btw, if you want to implement undo I'd check the UndoManager from mst-middlewares

**Comment by edbras** [comment]
Hmmm, yes sounds logical, given the fact that every node on the tree should have a unique id.

But shouldn't mst be smart enough to take that into account? Maybe throw an exception, or clone it and put it in some isolated tree space. Just a thought.

**Comment by xaviergonz** [comment]
To be more precise it has to be unique per tree and per type, so two different types (models) can have a same id and be on the same tree.

**Comment by xaviergonz** [comment]
About being smart enough, it doesn't really know what are valid identifiers for your model.

Also see https://github.com/mobxjs/mobx-state-tree/issues/239#issuecomment-473420957
