### ISSUE TITLE
Production Mode MST Error message is too vague.

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#1304]
**_Feature request_**

**Is your feature request related to a problem? Please describe.**
Currently, if I try to do a `map.put` operation on a complex model with a different type, I get the following error. When this error happens in the production, the relevant stack information is removed in the error object that was originally thrown, making debugging extremely difficult in a very complex system (us). We would like more relevant information to be shown so we can debug the issue more easily. (We want to know the stack of root cause in our code and more context in regards to how the MST failed).

Because our production users get message below and they have no idea as what happened, they just send us information like this to the developers, and it is difficult for us to tell what is wrong unless we run our local instance and reproduce the issue with exact steps.
![image](https://user-images.githubusercontent.com/20207137/58664369-80748480-82fc-11e9-840e-2033f7e69c43.png)

Note that both message and stack does not provide much relevant information.
![image](https://user-images.githubusercontent.com/20207137/58664488-c0d40280-82fc-11e9-8a89-623def56c305.png)

I was able to get the root stack where the MST error was caused (our code) in chrome dev tool. I am unsure as why that information is omitted in the stack.

Some others are also experiencing this issue: https://medium.com/@jiyinyiyong/some-pain-points-using-mobx-state-tree-in-our-team-f4e38890d66

**Describe the solution you'd like**
More relevant error message and stack trace.

**Describe alternatives you've considered**
Importing typecheck directly and use it every operation (Very cumbersome)
Setting NODE_ENV to something other than "production", but this is a hack.

**Are you willing to (attempt) a PR?**
* [ x ] Yes
* [ ] No

**Comment by xaviergonz** [comment]
Which error reporting system are you using? Maybe there's some config to allow them to show the full stack trace rather than just the beginning? The whole stack trace should be there (like you saw in chrome dev tools), it is not like MST is trimming it on purpose :)

That being said, feel free to submit a PR if you think the error reporting can be improved

**Comment by OverseePublic** [comment]
One another question. Why does this operation fail? When do we allow model creation without proper type checking and when do we force fail on prod mode? Should we fail but let the application proceed instead of hard stopping? Basically, i see a convuluted typechecking with fail stop. What is the reason behind this design? Any explanations are helpful! Thanks for your time

**Comment by OverseePublic** [comment]
Could @mweststrate perhaps help us understand? I need this to propagated to our very large team. We serve U.S federal level clients and we would like to know the reasoning behind it.

Michael, if you could also advise us in terms of enabling typechecking while leaving NODE_ENV=production it would be helpful. We are considering enabling typchecking in production. The documentation clearly states that the MST authors would advise against it, but what are the consequences of not following MST's recommendations? If so how could typechecking be enabled in production?

**Comment by mweststrate** [comment]
You can still force type checking at specific points (typically, the edges of your application) by calling `Type.is` or `Type.validate`, which gives all the validation errors, as done [here](https://github.com/mobxjs/mobx-state-tree/blob/5e7b9c7636e1d401e0694a5ad5aa2b83b1e54949/packages/mobx-state-tree/src/core/type/type.ts#L340-L342) (probably we should expose a utility). If you do that just before the offending line in your code (as shown in the full stack trace), that should reveal in detail why the type is invalid. 

The only difference between prod and dev, is that in both cases it should have failed, but that in DEV the error message just should be clearer. The errors are different, because in prod this fails at a later point in time, as the first check is optimized away. So manually bringing the check in again should give better details

**Comment by OverseePublic** [comment]
I think our goal is enabling typechecking on every `instantiation` and `update` is there a good way to enable that? I think it might actually decrease performance since it goes through typeCheck. I think you meant `edge` of application as the specific case of updating or creating mobx instances, but is it also possible to do typechecking all the time with NODE_ENV=production? And is it a recommended approach? What's the consequence of not following the recommendation?

Thanks for your time.

**Comment by mweststrate** [comment]
In principle there is no problem in doing so from MST side. but
NODE_ENV=production will have other unforeseen side effects, such as
unoptimized React, possible non-minified webpack etc. So it is probably
better to make this configurable in MST. A PR is welcome. (For example:
`configure({ enableTypeChecking: "always" })`)

**Comment by OverseePublic** [comment]
I have created a PR below. I believe it needs work. I will work on your suggestion as a downstream.

https://github.com/mobxjs/mobx-state-tree/pull/1332

**Comment by mweststrate** [comment]
Released #1337 in 3.14.1
