### ISSUE TITLE
Update todo example in codesandbox so it works with mobx-react v6

### ISSUE THREAD

**Issue by rdewolff** [mobxjs/mobx-state-tree#1312]
The CodeSandBox version linked in the `README.MD` file is not working.

Cf. https://github.com/mobxjs/mobx-state-tree/blame/master/README.md#L57

**Comment by FredyC** [comment]
I assume you mean this?

![image](https://user-images.githubusercontent.com/1096340/59152164-161bbc80-8a3f-11e9-8732-d7530c1ccf79.png)

Well, it should be fixed in that template for sure, not sure who has access to the team in there.

It's either about upgrading React to 16.8 or downgrading mobx-react to V5.

**Comment by rdewolff** [comment]
We could simply fork and update the address of the example sandbox.

**Comment by FredyC** [comment]
Sure, that's one path, but it would be nice to keep those examples under the common team in CodeSandbox.

@xaviergonz @k-g-a Any chance you have access there?

**Comment by xaviergonz** [comment]
I just fixed mobx-react to version 5, since the example uses views to create components and views expect functions, but the new observer implementation returns on object.

I'll leave this open though so the sample gets eventually fixed to use components not put inside views.

Also I gave you permissions to the codesandbox team @FredyC in case you might want to give a try at fixing it yourself (just open the code sandbox, project info, unfreeze it, make changes, save, freeze again)

**Comment by coolsoftwaretyler** [comment]
Gonna close out this issue since it's quite old and seems resolved. Thanks, all!
