### ISSUE TITLE
MST 3 LTS

### ISSUE THREAD

**Issue by OverseePublic** [mobxjs/mobx-state-tree#1320]
**_Question_**
How long will MST3 will be supported for legacy browser?

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Our codebase is 100000+ lines and we would like to know how long MST3 will be supported. Will this be a LTS version for legacy browser? Does MST plan to ever deprecate legacy browser (ie11)? We would like to understand the roadmap for MST for our internal discussion.

Thank you for your time. @mweststrate

**Comment by mweststrate** [comment]
All the work in this project is voluntarily and can be used for free. Yet,
since nobody is really being paid to keep the lights on, I cannot offer you
any SLAs. But if longevity is important to you, which it seems with 100K
lines, it might be time long past due time to contribute back through the
open collective or helping out with maintenance :)
https://opencollective.com/mobx.

**Comment by mweststrate** [comment]
That being said, there are currently no plans to no longer support MobX 4,
in other words, no plans to drop IE 11 support

**Comment by OverseePublic** [comment]
Thanks a lot Michael!
