### ISSUE TITLE
Why do I need the snapshot when composing trees?

### ISSUE THREAD

**Issue by Maaartinus** [mobxjs/mobx-state-tree#1356]
Not sure, if this is a bug or just a misunderstanding.

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Sandbox: https://codesandbox.io/embed/why-the-snapshot-1f8s3

**Describe the expected behavior**
I'd expect that I could create a new Root via
```
  const manager = Manager.create({});
  return Root.create({ manager });
```

**Describe the observed behavior**
... but instead I needed
```
  const managerObj = Manager.create({});
  const manager = getSnapshot(managerObj);
  return Root.create({ manager });
```

**Comment by mweststrate** [comment]
Your sandbox doesn't work for me, so not sure what you mean by "I need". Do you need to fix a compile error or a runtime error? 

If you are getting a compile error here, you might want to check out `cast`. But as far as MST is concerned, both patterns are valid. TS however might not be able to handle both pattern, so, in some cases it might give false negatives. Because the MST type system is more powerful than the TS type system, not everything "fits" nicely. Make sure to check out the typescript specific section in the readme. It has quite some tips and tricks.

**Comment by Maaartinus** [comment]
Sorry, I've reused my sandbox for another problem and mixed things up. I'm going to re-read the readme and I guess, `cast` is what I  need; otherwise I'll reopen.
