### ISSUE TITLE
TypeScript performance

### ISSUE THREAD

**Issue by RWOverdijk** [mobxjs/mobx-state-tree#1406]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

I have no idea where or why exactly but sometimes my IDE (webstorm) goes insane, running 100% on all my cores in some odd cases.

I've found that if I do not specifically state the source of a store for example, this happens. One such example is:

```ts
export class SpaceScreen extends Component<SpaceProps, SpaceState> {
  get venueStore() {
    return this.props.rootStore.venueStore as Instance<typeof VenueStore>;
  }
}
```

If I don't add the `as Instance<typeof VenueStore>` webstorm tries to destroy my macbook.

Another issue I've found is using getParent (rootStore) never allows me to type properly, saying:

> ... implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

if I try:

```ts
const rootStore = (getParent(self) as Instance<typeof RootStore>);
```

Maybe this is something that's known, but it's pretty hard to figure out why these things happen.

**PS:** Are there plans to give typescript more love with MST? Or doesn't it need any and is my thought on that wrong?

**Comment by Bnaya** [comment]
it happens to me in vs code as well.
it's due to the inference complexity.

Take a look on:
https://github.com/microsoft/TypeScript/issues/25023#issuecomment-453639378
in the linked comment there's my "workaround"

**Comment by RWOverdijk** [comment]
I'll give that a go. But it doesn't fix the:

> implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

Do you have any tricks for that as well?

**Comment by Bnaya** [comment]
Take a look at:
https://codesandbox.io/s/mst-issue-1406-olsn3

**Comment by RWOverdijk** [comment]
@Bnaya I meant this: https://codesandbox.io/s/brave-lederberg-1dqpo?fontsize=14

Look in `TestStore.ts`. 

![image](https://user-images.githubusercontent.com/781745/67668426-3574a100-f970-11e9-9d7e-ff651b9c98be.png)

**Comment by terrysahaidak** [comment]
@rwoverdijj did you try to use generic patam with getParent?

**Comment by kenaku** [comment]
> implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

This happens when you use getRoot() or getParent() in views/actions. 
You have to explicitly set return values of that views/actions, like so: 
```.views(self => ({
    get store(): IStore {
      return getRoot(self)
    },
    get formattedBalance(): string {
      return this.store.language
    },

**Comment by RWOverdijk** [comment]
@kenaku I don't understand what you're saying. Having a getter (assuming you mean a view?) like this won't work if I use "this" and the context isn't the same (which happens frequently).

Also not sure what "IStore" is.

In any case I tried it and it doesn't solve the issue (you can solving try it here:  https://codesandbox.io/s/brave-lederberg-1dqpo?fontsize=14 and see what I mean).

**Comment by RWOverdijk** [comment]
@terrysahaidak It's RWOverdijk 😄 And it doesn't make a difference. I tried getParentOfType, I tried getParent with generic `typeof RootStore` and I tried generic `Instance<typeof RootStore>`. All of which yield the same result. Also reproducable in the codesandbox link.

**Comment by mweststrate** [comment]
The error you get is correct, as TypeScript doesn't support recursive types at the moment (3.7 might change that!). Since it cannot express the type of your store depends on the output on the signature of that getter, which, to determine it's result type, needs to know the type of.... you see the circle. 

However, since interfaces can be recursive, you can fix this by using the trick explained in the  [docs](https://github.com/mobxjs/mobx-state-tree#using-a-mst-type-at-design-time): Make sure you introduce the type `export interface I{MODEL} extends Instance<typeof {MODEL}> {}`. 

After that, you can use that interface wherever needed to 'break' the cycle in the types. Without loosing strong typing. 

I applied the change here: https://codesandbox.io/s/serene-fog-oryt3. Note calling  `.test` is now strongly typed again. With this trick and sprinkling these interface any cycles can be fixed afaik. it might not always be immediately clear where you need it, but if you strongly type all action / view returns, it gets you quite far. (And I think that this a really good practice anyway). 

It is a bit cumbersome, but usually straightforward mechanism. So I guess we have to live with it until TS supports recursive types 😅

**Comment by terrysahaidak** [comment]
Sorry, @RWOverdijk, I've been typing from my phone without autocomplete :(

**Comment by RWOverdijk** [comment]
@mweststrate Well well well... Look at that. All right, I can live with that.

Isn't this whole "ISomeInterface" thing against the best practises/style guide? https://basarat.gitbooks.io/typescript/content/docs/styleguide/styleguide.html#interface

I don't know how much of an authority that doc is. I just remember a c# person saying they regret that convention and thought it would only make sense to then not apply it to TS.

Also, now that I have your attention... Are there plans to do a rewrite/happier implementation written using typescript? I have some ideas on how I'd like that to work and was thinking of folding my own solution. You're working on immer _(which btw does make me wonder, is that because you no longer like mst? Or because you have bigger plans? Or do you consider them unrelated?))_ and I don't want to put in effort somewhere if you end up working on exactly what I'm looking to build.

I know, this issue is not an AMA but you know. At least I tried 😄

**Comment by mweststrate** [comment]
Yes, I hate the I as well. However, since you need to find a name that
doesn't collide with your model type (although, maybe colliding is actually
fine, since one is a value and the other a type)..... So yeah, feel free to
leave out the I if that works :)

For an MST alternative that is better at TS, make sure to check
https://github.com/xaviergonz/mobx-keystone

Immer is solving an quite unrelated problem, and MST I never worked that
much on myself :)

**Comment by RWOverdijk** [comment]
@mweststrate  Nice, thanks for sharing that. I'll take a look.

I'll name my interfaces something other than II118nStore for now 😄 Maybe just a clear name like I18nStoreInstance and I18nStoreSnapshotIn. A bit long but clear.

Thanks again, everything works now :)
