### ISSUE TITLE
Difficulty to debug app.

### ISSUE THREAD

**Issue by tomitrescak** [mobxjs/mobx-state-tree#141]
When using mobx state tree all of app's function calls are wrapped into VM call with a following content:

```js
(function(f
/*``*/) {
return function addModules() { return f.apply(this, arguments)}
})
```

The name of the function in the call stack is correct, but the content is the one above. This makes it quite difficult to debug the code. Is this a fault of my bundler? "Fusebox". Are you experiencing the same on webpack?

**Comment by mattiamanzati** [comment]
Uhm, do you refer to model actions?

**Comment by mweststrate** [comment]
Pretty sure it originates from here: https://github.com/mobxjs/mobx-state-tree/blob/a1ca6a4dc3f7973367ed97337c33a84765b2c269/src/utils.ts#L104

Which is only there to properly name dynamically created functions, so that the stacktraces are more readable. However, since `Object.defineProperty(f, "name", ...)` is supported in most browsers, that is properly a cleaner solution (`f.name = X` is forbidden in JS)

**Comment by tomitrescak** [comment]
Thanks for considering this! Will be very helpful!
