### ISSUE TITLE
Compatibility with jsDoc

### ISSUE THREAD

**Issue by stoefln** [mobxjs/mobx-state-tree#1424]
**_Feature request_**
Support jsDoc

**Is your feature request related to a problem? Please describe.**
I am trying to use jsDoc for my mobx-state-tree powered app but I am having issues with it.
Visual studio code does not show me the right properties of the corresponding type (in fact it shows the wrong ones):
See here: 
https://i.stack.imgur.com/m8XYq.png

jsDoc is a huge help with other types and saves me hours of debugging every week! I posted on [stackoverflow](https://stackoverflow.com/questions/58752040/how-can-i-use-jsdoc-with-mobx-state-tree/58891125), and on [spectrum](https://spectrum.chat/mobx-state-tree/general/how-can-i-use-jsdoc-with-mobx-state-tree~b65a3bfb-13e3-419e-80ef-47ed1a6efdea), but since I didn't get any useful feedback I am assuming that jsDoc is just not working with MST.

**Describe the solution you'd like**
when I annotate method parameters with MST types, I would like the type checking features and code completion of visual studio code to work.

**Describe alternatives you've considered**
It seems that typescript would solve my issue. However, there are downsides to TS and I don't want to switch at this point (jsDoc works really well for me)

**Are you willing to (attempt) a PR?**
* [X] Yes (if I knew where to start, it's not clear for me why VS code is not able to deal with the MST types)
* [ ] No

**Comment by mweststrate** [comment]
It is unclear to me whether your issue is that JSDoc is not showing JSDoc comments, or that autocompletion shows the wrong members for the `step` istance in your screenshot. The first might very well the case, but in your screenshot the second seems to be the problem. That should normally work, and might be a problem in your setup.

**Comment by stoefln** [comment]
My problem is that the autocompletion shows the wrong members of the step instance.
I just tried in codesandbox and I am experiencing the same issue. 

<img width="581" alt="Screenshot 2019-11-19 at 16 24 44" src="https://user-images.githubusercontent.com/562800/69160148-59e41900-0ae9-11ea-9121-fee65d8b11cc.png">

Pls check:
https://codesandbox.io/s/mobx-state-tree-todolist-e4r3p

**Comment by mweststrate** [comment]
If I autocomplete on `store.` it is correct. On `store1.` you won't get
anything useful, because it is declared as TodoStore, but that is the type
of the model (the class itself you could say), not the type of the
instance. In TypeScript can get the type type of the instance as explained
in the docs. So that should roughly look like:

/**
*
* @param {typeof TodoStore.Type} store1
*/
function checkStore(store1){
store1.unfinishedTodoCount
}

**Comment by stoefln** [comment]
Wow, that works and that's amazing!
Sorry, I was not aware that the "Typescript" section of the docs was relevant for me since I don't use typescript in my app. Thanks so much!

**Comment by mweststrate** [comment]
Your IDE uses typescript for autocompletion. Whether you like it or not :)
