### ISSUE TITLE
Typescripts/Javascript set hint not correctly in overriding props

### ISSUE THREAD

**Issue by hiep294** [mobxjs/mobx-state-tree#1473]
I design a models which can be extend like this: 
```
const ProductList = types.model({
  items: types.map(types.model({
    price: types.optional(types.string, '')
  }))
})

const ProductListExtend = types.compose(
  ProductList,
  types.model({
    items: types.map(types.model({
      price: types.optional(types.number, 1)
    }))
  })
)

const List = ProductListExtend.create()
List.items.forEach(item => {
  // item is showing that it contain a string price, but a number is expected
})
```
In design above, items of ProductListExtend will be a map list of item which has price is a **number**. however, item is showing a hint that containing a price is a **string**.
My question is: Is there any way to show a hint correctly in javacriipt or typescript

**Comment by mweststrate** [comment]
I strongly recommend against redefining the type of an existing property,
it is gonna be very confusing for future you :)

**Comment by hiep294** [comment]
I have many lists like types.model({items: types.map(A)}) with the same actions. I put these actions into GeneralList, also need to define 'items' prop in GeneralList, because these actions will apply the a specific result to items. in overview:

```
const GeneralList = types.model({
  items: types.map(GeneralModel)
}).actions(...common actions required 'items' prop)

const ListOfA = types.compose(
  GeneralList, 
  types.model({
    items: types.map(A)
}))
```

That's why I would like to redefine the type

**Comment by coolsoftwaretyler** [comment]
Hey @hiep294 - I know it's been a while since anyone got back to you here, but I think @mweststrate has a good point that re-defining the properties is an anti-pattern here.

What you might consider doing instead is defining some utility functions that don't know anything about MST at all, and using them in the `actions` block for better code reuse.

Is this still a relevant problem for you? Do any of these suggestions help out? Let me know and we can try to resolve it. Otherwise, I'll close this issue out if I don't hear back in two weeks or so.

**Comment by k-g-a** [comment]
@coolsoftwaretyler , just wanted to mention that this is the same as [1403](https://github.com/mobxjs/mobx-state-tree/issues/1403).

@hiep294 , if this is still relevant, check out the proposed workaround from the above issue.

**Comment by coolsoftwaretyler** [comment]
Thanks @k-g-a! Good call. I'm going to close this issue out in favor of the workarounds in #1403 + perhaps some day we'll add some kind of official support to if (PRs welcome from the interested).

Thanks y'all!
