### ISSUE TITLE
Is there a way other than `unprotect(state)` to let different branches call actions on each other?

### ISSUE THREAD

**Issue by garrettg123** [mobxjs/mobx-state-tree#1479]
**_Question_**

* [X] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Is there a way other than `unprotect(state)` to let different branches call actions on each other? It's hard to constantly do make intermediate functions like:
```js
getRoot(self).callActionOnMyOtherModel()
// Ideally: getRoot(self).myOtherModel.myAction()
```
Because it requires creating an extra action.

**Comment by coolsoftwaretyler** [comment]
Hey @garrettg123 - sorry it took so long for anyone to get back to you here in MobX-State-Tree. I don't know if I totally understand the problem you're trying to solve. 

If you're still interested in digging into this, can you clarify for me what your `callActionOnMyOtherModel` looks like? Or provide a [CodeSandbox](https://codesandbox.io/s/y64pzxj01) example instead?

I totally understand if you have since moved on from the problem. In which case we can just close this out. 

If I don't hear back in about two weeks, I'll close this issue. Thanks!

**Comment by coolsoftwaretyler** [comment]
No response for the past two weeks - gonna close this out. Sorry we couldn't help more!
