### ISSUE TITLE
The todo demo in document rewrite by typescript but has type error

### ISSUE THREAD

**Issue by zhuyuedlut** [mobxjs/mobx-state-tree#1599]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

Hi guys, I want to rewrite the todo demo in document by typescript, but when I try to rewrite the rooter I meet a question.
That is when I use views api in RootStore, like this, but I get the type error. How can I fix this

![2020-11-05_105720](https://user-images.githubusercontent.com/24931666/98192368-dd468680-1f55-11eb-9406-fa02e3e9a796.png)

**Comment by Relaxe111** [comment]
Project is possiblity undefined you can fix in two ways
`Item?.done` or `item.done! `Second one is not recommended because you can get undefined st run time. First
 One you can add some aditional logic to handle situations when you get undefined e ex to put a default value if done is undefined like `item?.done ?? "Default value"`

**Comment by coolsoftwaretyler** [comment]
Hey @zhuyuedlut, I think @zhuyuedlut's answer is correct here, so I'm going to close this out.

Thanks y'all!
