### ISSUE TITLE
Using detach with an array, it cannot be reattached to the tree

### ISSUE THREAD

**Issue by evelant** [mobxjs/mobx-state-tree#1611]
**_Bug report_**

* [ X ] I've checked documentation and searched for existing issues
* [ X ] I've made sure my project is based on the latest MST version
* [ X ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/cool-lake-w7co5?file=/src/App.tsx

**Describe the expected behavior**
`const detachedArray = detach(self.myArray); self.someOtherArray = cast(detachedArray);` should detach `myArray` and its contents then reattach it at `someOtherArray`.

**Describe the observed behavior**
`[mobx-state-tree] Cannot add an object to a state tree if it is already part of the same or another state tree. Tried to assign an object to '/drawPile/0', but it lives already at '/3'`

It appears that the contents of the array are not marked as detached properly.

I'm modeling a card game where I want to shuffle the "discard pile" and replace the "draw pile" with the shuffled cards. If I do it as above by detaching the array MST throws the "already lives" error. To work around this I must individually detach each element of an array instead of detaching the whole array. 

See this codesandbox: https://codesandbox.io/s/cool-lake-w7co5?file=/src/App.tsx

I expected the `reshuffleBad` and `reshuffleGood` actions to be identical, but `reshuffleBad` throws the above error.

Here's a code snippet from the sandbox
```
const CardsModel = t
  .model({
    discardPile: t.array(CardModel),
    drawPile: t.array(CardModel)
  })
  .actions((self) => ({
    reshuffleBad() {
      //Crashes!
      const discards = detach(self.discardPile);
      const draws = detach(self.drawPile);
      const shuffled = _.shuffle([...discards, ...draws]);
      self.drawPile = cast(shuffled);
    },
    reshuffleGood() {
      //No problem
      const discards = self.discardPile.map(detach);
      const drawDeck = self.drawPile.map(detach);
      const shuffled = _.shuffle([...discards, ...drawDeck]);
      self.drawPile = cast(shuffled);
    }
  }));
```

**Comment by coolsoftwaretyler** [comment]
Hey @evelant - I'm sorry it took so long for anyone to get back to you here. I know it's literally been years.

I think I was able to get the solution for you (or at least, ChatGPT was). I put your CodeSandbox into ChatGPT with some context, and [this seems to be working now](https://codesandbox.io/s/wandering-wind-7gdy44?file=/src/App.tsx).

Here's what ChatGPT says about the updated code:

> In this updated code, the reshuffleBad() action and the reshuffleGood() action have been modified.
> 
> In the reshuffleBad() action, the individual detachment of array elements has been replaced with mapping detach over the arrays (self.discardPile.map(detach) and self.drawPile.map(detach)). After that, the replace() method is used instead of a direct assignment (self.drawPile.replace(shuffled)) to update the drawPile array.
> 
> In the reshuffleGood() action, each element of the discardPile and drawPile arrays is detached using map((card) => detach(card)). Then, the detached arrays are combined, shuffled, and assigned back to self.drawPile using replace().
> 
> These modifications ensure that the elements are properly detached and the arrays are correctly updated, resolving the issue you encountered.
> 
> Now, when you click the "bad shuffle" button, you will no longer encounter the error, and the shuffling behavior should work as expected. Similarly, the "good shuffle" button will also shuffle the cards correctly without any errors.

I'm going to label this to be closed. If I don't hear back from you in a week or two, I'll close it out. But if this is still relevant to you, or if you found a similar solution on your own, I'd love to hear about it!

**Comment by coolsoftwaretyler** [comment]
Gonna close this out. Sorry again about the delay on the response time. Hopefully the fixes here help you or someone else!

**Comment by tigger0jk** [comment]
From what I understand the initial report is:
- I would like to call "detach" on an entire array, rather than mapping "detach" over every element in the array (which calls them one at a time)
- An example of this is provided, where detaching the whole array doesn't work / isn't supported, but mapping detach over every element works.

The "fixed" code from the codesandbox simply changes both examples into mapping over detach, a-la the "good" example. This is simply using the same workaround that the initial report notes as a workaround.
```
    reshuffleBad() {
      const discards = self.discardPile.map(detach);
      const draws = self.drawPile.map(detach);
      const shuffled = _.shuffle([...discards, ...draws]);
      self.drawPile.replace(shuffled);
    },
    reshuffleGood() {
      const discards = self.discardPile.map((card) => detach(card));
      const drawDeck = self.drawPile.map((card) => detach(card));
      const shuffled = _.shuffle([...discards, ...drawDeck]);
      self.drawPile.replace(shuffled);
    }
```

The original reporter doesn't note this, but it is observably the case in my situation where I have a few thousand elements in the list in question - mapping over each one individually is very slow (each operation triggers an update?). I'm very new to mobx and probably doing other things wrong / misunderstanding what is possible, but it seems like detaching the whole array in one call could be more efficient.

But regardless, this is a question of "why can't I simply detach the _whole_ array, rather than detaching every element". Possible answers might be like "you logically can't do that because X" or "if we did that it would simply map over each element internally" or "we could support it but haven't yet" or whatever but not "here's how you map to detach each element individually" - that is provided in the question.

**Comment by coolsoftwaretyler** [comment]
Hey @tigger0jk - good points! My response was from early days when I started pitching in here and you're right I missed some important details. My bad for leaving this thread dissatisfying!

A year later, my instinct is that we should check if detach runs recursively against its children. It's possible it doesn't, which would be why you can't detach some intermediate node and have its children detached as expected. 

It's also possible that _is_ the intention, but there's some kind of bug in the array type that breaks it.

I'm away from my computer at the moment but will investigate a little more. If you're poking around, I encourage you to do the same and would be curious about what you find!

I will return to this thread later regardless.

Good eye and thanks for reviving the thread!

**Comment by coolsoftwaretyler** [comment]
Took a second read of the issue and I think it's a little simpler than all that/not a bug:

When you detach the array from the original tree, the array becomes a second tree, where the array itself is the root, and the elements inside the array still have paths in the second tree (and importantly: the array is their parent).

Since those elements belong to a second tree, and since MST nodes can only belong to exactly one tree, you need to detach them from tree 2 before doing anything with them.

I think (but need to double check) once a node no longer has a parent, it should be able to be attached to another tree 

I'll spin up another code sandbox to verify and demonstrate later tonight.

**Comment by coolsoftwaretyler** [comment]
Yup, that's the trick here. In [this Code Sandbox](https://codesandbox.io/p/sandbox/1611-demo-hvqz5k?file=%2Fsrc%2Findex.ts%3A73%2C1):

1. Set up a CardModel to hold individual cards
2. Set up a CardsModel to hold discard/draw piles, which are arrays of CardModels
3. Write the `reshuffleBad` and `reshuffleGood` actions, but I took out the final `self.drawPile` assignment to prevent errors and re-parenting
4. Set up four cards 1-4. Put cards 1 and 2 in a discard pile of one CardsModel, and cards 3 and 4 in the draw pile
5. Run `reshuffleBad` without the final assignment, and check the parents of each of the first four cards (output below, but the parents are array objects)
6. Set up four more cards, 5-8. Put them in a new CardsModel in the same order.
7. Run `reshuffleGood` without the final assignment, and use `hasParent` to check if the cards have parents (since `getParent` will throw if there is none, and in this case, there is no parent).

```ts
import { cast, detach, t, getParent, hasParent } from "mobx-state-tree";
import _ from "lodash";

const CardModel = t.model("CardModel", {
  name: t.optional(t.string, "card here"),
});

const CardsModel = t
  .model({
    discardPile: t.array(CardModel),
    drawPile: t.array(CardModel),
  })
  .actions((self) => ({
    reshuffleBad() {
      //Crashes!
      const discards = detach(self.discardPile);
      const draws = detach(self.drawPile);
      const shuffled = _.shuffle([...discards, ...draws]);
      // self.drawPile = cast(shuffled);
    },
    reshuffleGood() {
      //No problem
      const discards = self.discardPile.map(detach);
      const drawDeck = self.drawPile.map(detach);
      const shuffled = _.shuffle([...discards, ...drawDeck]);
      // self.drawPile = cast(shuffled);
    },
  }));

const card1 = CardModel.create({ name: "1" });
const card2 = CardModel.create({ name: "2" });
const card3 = CardModel.create({ name: "3" });
const card4 = CardModel.create({ name: "4" });

const cards = CardsModel.create({
  discardPile: [card1, card2],
  drawPile: [card3, card4],
});

cards.reshuffleBad();

const card1Parent = getParent(card1);
const card2Parent = getParent(card2);
const card3Parent = getParent(card3);
const card4Parent = getParent(card4);

console.log("Card 1 parent after bad reshuffle: ", card1Parent);
console.log("Card 2 parent after bad reshuffle: ", card2Parent);
console.log("Card 3 parent after bad reshuffle: ", card3Parent);
console.log("Card 4 parent after bad reshuffle: ", card4Parent);

const card5 = CardModel.create({ name: "5" });
const card6 = CardModel.create({ name: "6" });
const card7 = CardModel.create({ name: "7" });
const card8 = CardModel.create({ name: "8" });

const cards2 = CardsModel.create({
  discardPile: [card5, card6],
  drawPile: [card7, card8],
});

cards2.reshuffleGood();

const card5Parent = hasParent(card5);
const card6Parent = hasParent(card6);
const card7Parent = hasParent(card7);
const card8Parent = hasParent(card8);

console.log("Card 5 hasParent after good reshuffle: ", card5Parent);
console.log("Card 6 hasParent after good reshuffle: ", card6Parent);
console.log("Card 7 hasParent after good reshuffle: ", card7Parent);
console.log("Card 8 hasParent after good reshuffle: ", card8Parent);
````

The output in the console is:

```
Card 1 parent after bad reshuffle:  (2) [Object, Object] // If you open this up you'll see it's an array that matches the array we put card1 into.
Card 2 parent after bad reshuffle:  (2) [Object, Object] // If you open this up you'll see it's an array that matches the array we put card1 into.
Card 3 parent after bad reshuffle:  (2) [Object, Object] // If you open this up you'll see it's an array that matches the array we put card1 into.
Card 4 parent after bad reshuffle:  (2) [Object, Object] // If you open this up you'll see it's an array that matches the array we put card1 into.
Card 5 hasParent after good reshuffle:  false
Card 6 hasParent after good reshuffle:  false
Card 7 hasParent after good reshuffle:  false
Card 8 hasParent after good reshuffle:  false
```

I think this behavior comes from `createObjectNode`, where we check if a node has a parent. If it does, we throw the error as reported originally. Here's the specific line of code on current `master`: https://github.com/mobxjs/mobx-state-tree/blob/7f3545c6ef645011214049163d44d8b7f407c631/src/core/node/create-node.ts#L25

I hope that clarifies a little bit! My original answer definitely didn't paint the entire picture, and this stuff is trickier than I'd like it to be. I find myself often running these little experiments to validate and reinforce my understanding of all the rules. MST is great for enforcing conventions, but they definitely require a little investigation to fully grok.

**Comment by tigger0jk** [comment]
Thanks for the speedy and detailed response!

> When you detach the array from the original tree, the array becomes a second tree, where the array itself is the root, and the elements inside the array still have paths in the second tree (and importantly: the array is their parent).
> 
> Since those elements belong to a second tree, and since MST nodes can only belong to exactly one tree, you need to detach them from tree 2 before doing anything with them.

In my case I switched from using an array to using a map and then only set changed or new values to fix my perf issues.

However if I still had my array case I would try in the "bad shuffle" case, detaching the array, then detaching every node (from the second tree it's moved to), to see if that changes the perf. Unfortunately not in a position to run that experiment anymore (and probably the real issue is how I'm observing updates).

I can't see the code sandbox you posted (maybe private?) to test if you can detach the array then detach all elements after and if it still works. Although code-wise it's simply extra work, unsure if there would be some positive perf implications in some cases (no one's observing the second tree?, so maybe?)

**Comment by coolsoftwaretyler** [comment]
Whoops, I always do that with sandboxes. Just made it public.

I'd have to see some more details to say anything useful about the performance question here. I don't think I totally understand what you're seeing/measuring there. If you send another code snippet I can take a look!

**Comment by tigger0jk** [comment]
Nah I don't actually have an example case for it anymore so don't worry about it. Thanks though!
