### ISSUE TITLE
Automatically deserialise JSON arrays into maps, when types.map is used

### ISSUE THREAD

**Issue by fabiosussetto** [mobxjs/mobx-state-tree#165]
In this example:
http://jsbin.com/noyehujowa/1/edit?js,console
I added a ```tags``` map to the Todo model. When I try to pass a json snapshop, MST complains about the ```tags``` property not being an object (it expects {} but I'm passing [] on purpose).
I think it would be nice instead if MST could detect that I'm using a mobx map for ```tags``` and automatically create the map from my array. Internally, it could even use ```map.put``` so that identifiers are used as keys.
This can be a quite common scenario, normally you'd get the tags as a JSON array from your API, but you may want to use a map for quick lookups. Also, note that AFAIK mobx maps can already be constructed from entries arrays.

Thanks!

**Comment by mattiamanzati** [comment]
Hi!
Yeah, basically what you mean is that if map snapshot is an array, and given child has an identifier, loop through the array and create a map of that items retriving the ID?
I think it's kinda a special usage, will be for sure easy to implement once #100 are in, so maybe instead of hardcoding that behaviour, #100 would be a better solution for implementing this.

**Comment by fabiosussetto** [comment]
Yeah agree, snapshot hooks seem like a good generic way to support this in user-land.
