### ISSUE TITLE
Error with mobx 6.1.0

### ISSUE THREAD

**Issue by vtrphan** [mobxjs/mobx-state-tree#1653]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

**Describe the expected behavior**

no error

**Describe the observed behavior**

i got this error after updating to Mobx 6.1
`Error: [MobX] Cannot apply '@action' to 'ComplexType.prototype.create':
The field is already decorated with '@action'.
Re-decorating fields is not allowed.
Use '@override' decorator for methods overriden by subclass.`

i think this error is caused by MST, no?

**Comment by urugator** [comment]
This can be solved simply as suggested in error by changing `@action` to `@override` in `ComplexType`.

However there is a bigger issue with `actions` being non-`writable` since `6.1.0` namely here:
https://github.com/mobxjs/mobx-state-tree/blob/d767e80654b138eb388a0ff8e9ece84d9c743c96/packages/mobx-state-tree/src/types/utility-types/snapshotProcessor.ts#L151
One way to handle this would be to create action manually (not via `makeObservable`):
```javascript
ComplexType.prototype.create = action(function create() { /**/ });
```
Is it feasible?

Or obviously by having `runInAction` inside the method at the cost of closure per invocation, not ideal perf wise...

Are there other places where non-configurability/non-writability could cause troubles?

**Comment by vtrphan** [comment]
are these suggestions for me or for the maintainers of MST?

**Comment by iChenLei** [comment]
@vtrphan It's for the maintainers of MST, so just keep use 6.0.x and wait maintainers to solve this problem.

**Comment by urugator** [comment]
Pushed a PR https://github.com/mobxjs/mobx-state-tree/pull/1656

**Comment by jesperp** [comment]
I spent a good couple of hours scratching my head on this, trying different package versions 😅
If you still get this error and use snowpack, make sure to clear snowpack cache:

`snowpack --reload`

**Comment by jamonholmgren** [comment]
Released as 5.0.1:

https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.1

**Comment by yuliankarapetkov** [comment]
I'm still getting the same error, although I'm using `5.0.1`. Here's my setup:

```
    "mobx": "^6.3.0",
    "mobx-react": "^7.1.0",
    "mobx-state-tree": "^5.0.1",
    ```

**Comment by iChenLei** [comment]
@yuliankarapetkov Can you create a new [issue](https://github.com/mobxjs/mobx-state-tree/issues/new?assignees=&labels=&template=bug-report.md) for your problem ? and share a minimal reproducation online demo(e.g. codesandbox, stackblitz). Thanks!
