### ISSUE TITLE
Snapshot is created/updated without reading any observable value

### ISSUE THREAD

**Issue by VitaliiK91** [mobxjs/mobx-state-tree#1658]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [ ] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
I use the following mobx configuration:
```javascript
configure({
    enforceActions: "observed",
    computedRequiresReaction: true,
    reactionRequiresObservable: true,
});
```

**Describe the expected behavior**
Should not get warnings

**Describe the observed behavior**
I get mobx warning on the first render of components using the store.
The warning: `derivation.ts:198 [mobx] Derivation ObjectNode@81.snapshot is created/updated without reading any observable value`

**Comment by coolsoftwaretyler** [comment]
Hey @VitaliiK91 and @austinbutler - sorry it took so long for anyone to get back to you here.

Unfortunately, I can't get access to that old Gitter thread. I know this issue is old, but I'm wondering: 

1. Did either of y'all find a good solution to the problem? If so, will you please post it here for others?
2. Is this still an issue for you? If so, can you please post a reproducible example?

I know this issue is pretty old, so no worries if you've moved on. Feel free to ignore and I'll close this out in two weeks or so.

**Comment by coolsoftwaretyler** [comment]
Been about two weeks, I'm gonna close this out. Sorry we never got around to this for ya!
