### ISSUE TITLE
https://spectrum.chat is closing and we need an alternative for MST discussions

### ISSUE THREAD

**Issue by elektronik2k5** [mobxjs/mobx-state-tree#1662]
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried the [spectrum channel](https://spectrum.chat/mobx-state-tree/general?tab=posts)

Hello and thanks for maintaining MST!

I've been responding in https://spectrum.chat/mobx-state-tree over the past couple of years. However, it is being shut down: https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5.

I suggest we try GitHub Discussions and if it doesn't work well, explore alternatives. I have zero experience with GitHub Discussions and this isn't a recommendation. Similarly, I'm not really familiar with other alternatives and have no recommendations for or against them.

Tagging a few people whom I've recently seen active here in the repo and/or in Spectrum: @EmilTholin @mweststrate @jamonholmgren @Bnaya @iswara108.

**Comment by mattruby** [comment]
Funny you should mention this @elektronik2k5.   @EmilTholin has begun looking into moving to github discussions.  

@EmilTholin any interest in moving sooner?

**Comment by EmilTholin** [comment]
Hey @elektronik2k5!

Yeah, like @mattruby points out we have been looking at alternatives, and right now it looks like we will indeed open up GitHub Discussion.

I think it will be better for us if we open up GitHub Discussions closer to August 10th, so that we don't split up the community too much, and have to answer questions in two places at the same time.

**Comment by AndrewMorsillo** [comment]
GitHub Discussions looks great and seems likely to be the best option because of the obviously tight GitHub integration but there are a couple other potentially good choices:

Discourse is IMO a very good platform in terms of organizing discussion and searchability. They offer free hosting for open source projects but it seems it's limited to 50k pageviews/mo https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

Zulip is another excellent platform for organized discussion, seems they do 100% free for open source projects https://zulip.com/

**Comment by EmilTholin** [comment]
We decided to go with [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)! Our [Spectrum community has been archived](https://spectrum.chat/mobx-state-tree?tab=posts) and is redirecting to GitHub Discussions as well.
