### ISSUE TITLE
`IMSTMap` type still has references to removed methods `toJS` and `toPOJO`

### ISSUE THREAD

**Issue by MarkLeMerise** [mobxjs/mobx-state-tree#1666]
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**
https://codesandbox.io/s/uhwdd

```ts
import { types } from "mobx-state-tree";

export const Thing = types.model("test", {
  a: types.map(types.number)
});

const thing = Thing.create({
  a: { a: 1 }
});

console.log(thing.a.toJSON()); // works
console.log(thing.a.toJS()); // no type error, but fn doesn't exist
console.log(thing.a.toPOJO()); // no type error, but fn doesn't exist
```

**Describe the expected behavior**
References to `toJS` and `toPOJO` should be type errors.

**Describe the observed behavior**
References to `toJS` and `toPOJO` are not marked as type errors and the calls fail at runtime.

On a side note, I looked through the changelog and release notes and couldn't find any references to these methods being removed. Was this a planned deprecation? Was it mentioned somewhere else that I missed?

**Comment by Strandinator** [comment]
I just looked at the `types.map` source code. If i understand it correctly the `toJSON`, `toJS` and `toPOJO` methods are directly from the MobX `ObservableMap` class.
The [MobX Changelogs](https://github.com/mobxjs/mobx/blob/8a1c5ba2cdaaaba4005f34dc45c5ae8fc80a6121/packages/mobx/CHANGELOG.md#600) state that those methods have been dropped in v6.0 

Since mobx-state-tree has MobX only as peer dependency it depends on your local MobX version.

**Comment by MarkLeMerise** [comment]
Thanks for taking care of it!
