### ISSUE TITLE
Is .sort exists in types.array ?

### ISSUE THREAD

**Issue by KatSick** [mobxjs/mobx-state-tree#175]
First of all, thanks all for this awesome library!

In typings there is an issue where .sort method are not available for ObservableArray, however it extends from Array interface.

I tried in playground, however, sort is not working..

Repro: https://goo.gl/cEKkbz

**Comment by mattiamanzati** [comment]
Uhm, instead of comparing you should return 0, -1 or 1 to properly sort :)

https://mattiamanzati.github.io/mobx-state-tree-playground/build/index.html#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20Todo%20%3D%20types.model('Todo'%2C%20%7B%0A%20%20%20%20id%3A%20types.number%2C%0A%20%20%20%20title%3A%20types.string%2C%0A%20%20%20%20prio%3A%20types.number%2C%0A%7D)%0A%0Aconst%20Store%20%3D%20types.model('Store'%2C%20%7B%0A%20%20%20%20todos%3A%20types.array(Todo)%2C%0A%20%20%20%20isByPrio%3A%20types.boolean%2C%0A%0A%20%20%20%20get%20list()%20%7B%0A%20%20%20%20%20%20%20%20if%20(this.isByPrio)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20this.todos%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.sort((a%2C%20b)%20%3D%3E%20a.prio%20-%20b.prio)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20return%20this.todos%3B%0A%20%20%20%20%7D%0A%7D%2C%20%7B%0A%20%20%20%20togglePrio()%20%7B%0A%20%20%20%20%20%20%20%20this.isByPrio%20%3D%20!this.isByPrio%3B%0A%20%20%20%20%7D%0A%7D)%0A%0Aconst%20store%20%3D%20Store.create(%7B%20todos%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20title%3A%20'My%20first%20todo'%2C%0A%20%20%20%20%20%20%20%20prio%3A%202%2C%0A%20%20%20%20%20%20%20%20id%3A%201%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20title%3A%20'My%20second%20todo'%2C%0A%20%20%20%20%20%20%20%20prio%3A%201%2C%0A%20%20%20%20%20%20%20%20id%3A%202%0A%20%20%20%20%7D%0A%5D%2C%20isByPrio%3A%20false%20%7D)%3B%0A%0Ainspect(store)%0A%0Aconst%20App%20%3D%20observer(%0A%20%20%20%20props%20%3D%3E%20(%0A%20%20%20%20%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cul%3E%7Bprops.store.list.map(t%20%3D%3E%20%3Cli%20key%3D%7Bt.id%7D%3E%7Bt.title%7D%2C%20%7Bt.prio%7D%3C%2Fli%3E)%7D%3C%2Ful%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cbutton%20onClick%3D%7B()%20%3D%3E%20props.store.togglePrio()%7D%3Eby%20prio%20%7Bprops.store.isByPrio%20%3F%20'ON'%20%3A%20'OFF'%7D%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20)%0A)%0A%0Arender(%3CApp%20store%3D%7Bstore%7D%20%2F%3E)%0A
