### ISSUE TITLE
How to write types for self in typescript?

### ISSUE THREAD

**Issue by xurenda** [mobxjs/mobx-state-tree#1848]
Hello everyone, I have a problem, I am using `mobx-state-tree` with `typescript`, I want to splitting actions but I don't know how to define the type of `self`:
```typescript
export const  M_Element = types.model({
  // ...
}).actions(elementActions)

// In another file
export const elementActions = (self: ???) => {
  // ...
}
```
How to write types for self in typescript?
I try:
```typescript
export const elementActions = (self: Instance<typeof M_Element>) => {
  // ...
}
```
But it gets a typescript error:
```
(ts7022)'elementActions' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer
```
Can anyone help me?

**Comment by Slooowpoke** [comment]
We had to use a few things to get this working because of issues with circular dependencies. 

You need to break the model into two, then define the type after. Otherwise, the type used in the elementActions will reference itself. 

```
const M_Element = types.model({
  // ...
})

export type MElementType = Instance<typeof M_Element>

export M_Element.actions(elementActions)
```

Then in your other file (make sure you import with the typescript import **type**
```
import type { MElementType } from './wherever';

export const elementActions = (self: MElementType) => {
```

This works fine until you have actions that call actions in the same file, then you have to do the above again, and export different types for different sets of actions. But at least they aren't all in one big file.

**Comment by xurenda** [comment]
@Slooowpoke Okay, thank you, help me solve the problem.
