### ISSUE TITLE
Is there a way to prevent exception throws？

### ISSUE THREAD

**Issue by ywcr** [mobxjs/mobx-state-tree#1864]
First of all, I'm sorry that my English is not very good.

Our team wanted to catch error messages during MST usage and prevent error throws from affecting page usage.

Is there an API to support it?

Thanks a million!!

**Comment by EmilTholin** [comment]
Hi @ywcr!

Do you think you could include a small code sample showing where you would like to catch an error? It might be throws for many different reasons with different strategies for catching them.

**Comment by coolsoftwaretyler** [comment]
Hey @ywcr - just following up on @EmilTholin's request. I'm going to mark this as needs more info for now, but since it's been a long time since this thread had activity, I'll close it out if I don't hear anything in the next two weeks or so.

If this is still an issue for you, please post some example code and I will be happy to help!

**Comment by coolsoftwaretyler** [comment]
Closin' it out. Thanks, all!
