### ISSUE TITLE
distinguish actions from state in a model

### ISSUE THREAD

**Issue by brucexiejunling** [mobxjs/mobx-state-tree#1963]
**_Feature request_**
as far as i know,  MST define actions and state(computed also) into a model object. as a domain model, i think, it's better to divide them apart,  since we declare them in different way, but we visit it the same way.

**Comment by antondomratchev** [comment]
Take a look at the philosophy behind MST design pattern. https://mobx-state-tree.js.org/intro/philosophy

**Comment by coolsoftwaretyler** [comment]
Since this would be a somewhat fundamental change to MST, and there hasn't been a ton of discussion here, I'm going to close out the issue for now.

@brucexiejunling - I know it's been a long time since anyone responded to this. I'm sorry about the delay. If you feel strongly about it, would you consider opening up [a discussion instead](https://github.com/mobxjs/mobx-state-tree/discussions)? We can talk about it over there if you'd like!
