### ISSUE TITLE
IModelType volatile typings are incorrect with strictNullChecks

### ISSUE THREAD

**Issue by KatSick** [mobxjs/mobx-state-tree#213]
Minimal repro:

```
import { types } from 'mobx-state-tree';
import { IModelType } from 'mobx-state-tree/dist/types/complex-types/object';

type NodeModelType = {};

type NodeModelState = {
  test: string | null;
};

type NodeModelAction = {
  afterCreate(): void;
};

type NodeModel = IModelType<NodeModelType, NodeModelState, NodeModelAction>;

export const testModel: NodeModel = types.model(
  {},
  {
    test: null
  },
  {
    afterCreate() {
      this.test = '';
    }
  }
);
```

With typecsript 2.4.0 and strictNullCheck: true, i receive next error: `[ts] Type '""' is not assignable to type 'null'.`

How to avoid this ?

**Comment by mweststrate** [comment]
I assume the compile error comes from the `afterCreate`? The model definition doesn't use your manually created types. Using `types.model<NodeModelType, NodeModelState, NodeModelAction>({...})`  will probably fix that. Otherwise try `test: null as (string | null)` instead of `test: null` in the state declaration

But note that you can define `NodeModel` simply as `type NodeModel = typeof testModel.Type`, in which case `NodeModel` will be produced from your `testModel`, rather than needing to keep the two definitions in sync manually. See also: https://github.com/mobxjs/mobx-state-tree#typescript--mst

**Comment by KatSick** [comment]
`I assume the compile error comes from the afterCreate?`
- yes.

Thanks, will try, and report back to you.

**Comment by KatSick** [comment]
`But note that you can define NodeModel simply as type NodeModel = typeof testModel.Type, in which case NodeModel will be produced from your testModel, rather than needing to keep the two definitions in sync manually. See also: https://github.com/mobxjs/mobx-state-tree#typescript--mst`

Unfortunately i can't, because of: https://github.com/mobxjs/mobx-state-tree/issues/137.

After types.model(...) i receive error `implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Comment by mweststrate** [comment]
Note that you can create self referring types by leveraging `types.late`, see for example: https://github.com/mobxjs/mobx-state-tree/blob/8e98428cf7a83224c62202461ddd953251d866b7/test/late.ts#L24

**Comment by KatSick** [comment]
@mweststrate thanks for help it works!
