### ISSUE TITLE
Copying tree nodes

### ISSUE THREAD

**Issue by evanblack** [mobxjs/mobx-state-tree#216]
What's the best way to copy a tree node? I know the `clone` and `detach` methods exist, but I need an additional node with it's own uuid. I've added a copy action to the "boxes" example like so:

```
const Arrow = types.model("Arrow", {
    id: types.identifier(),
    from: types.reference(Box),
    to: types.reference(Box)
}, {
  copy() {
    var c = getSnapshot(this)
    let copy = Arrow.create({
      id: randomUuid(),
      from: c.from,
      to: c.to
    })
    return copy
  }
})
```

Unfortunately, my `from` and `to` references don't seem to resolve and I get "Failed to resolve reference of type Box: 'BOXID'". I'm guessing its because it's unaware of the Store and I need to `applySnapshot` somehow.

**Comment by mattiamanzati** [comment]
Yeah, they aren't able to resolve because "from" and "to" points to a value that belongs to the store, and as you pointed out the copied arrow does'nt belong to it, so it can't resolve it. If you try to attach the new arrow somewhere in the store, they should resolve to that property :)
However, instead of setting from and to to the id, you can set directly to the resolved value, and MST will hold them even if they don't belong to the same tree :)
https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20React%20from%20%22react%22%0Aimport%20%7B%20types%2C%20getSnapshot%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0Aimport%20%7B%20inspect%2C%20render%20%7D%20from%20%22mobx-state-tree-playground%22%0A%0Aconst%20randomUuid%20%3D%20()%20%3D%3E%20(Math.random()%20*%2010000).toString(36)%0A%0Aexport%20const%20Box%20%3D%20types.model(%0A%20%20%20%20%22Box%22%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20%20%20%20%20name%3A%20%22hal%22%2C%0A%20%20%20%20%20%20%20%20x%3A%200%2C%0A%20%20%20%20%20%20%20%20y%3A%200%2C%0A%20%20%20%20%20%20%20%20get%20width()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20this.name.length%20*%2015%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20get%20isSelected()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!hasParent(this))%20return%20false%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20getParent(this%2C%202).selection%20%3D%3D%3D%20this%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20move(dx%2C%20dy)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.x%20%2B%3D%20dx%0A%20%20%20%20%20%20%20%20%20%20%20%20this.y%20%2B%3D%20dy%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20setName(newName)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.name%20%3D%20newName%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A)%0A%0Aexport%20const%20Arrow%20%3D%20types.model(%22Arrow%22%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20from%3A%20types.reference(Box)%2C%0A%20%20%20%20to%3A%20types.reference(Box)%0A%7D%2C%20%7B%0A%20%20copy()%20%7B%0A%20%20%20%20var%20c%20%3D%20getSnapshot(this)%0A%20%20%20%20let%20copy%20%3D%20Arrow.create(Object.assign(%7B%7D%2C%20c%2C%20%7B%0A%20%20%20%20%20%20id%3A%20randomUuid()%2C%0A%20%20%20%20%20%20from%3A%20this.from%2C%0A%20%20%20%20%20%20to%3A%20this.to%0A%20%20%20%20%7D))%0A%20%20%20%20return%20copy%0A%20%20%7D%0A%7D)%0A%0Aexport%20const%20AppStore%20%3D%20types.model(%0A%20%20%20%20%22Store%22%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20boxes%3A%20types.map(Box)%2C%0A%20%20%20%20%20%20%20%20arrows%3A%20types.array(Arrow)%2C%0A%20%20%20%20%20%20%20%20selection%3A%20types.maybe(types.reference(Box))%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20addBox(name%2C%20x%2C%20y)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20box%20%3D%20Box.create(%7B%20name%2C%20x%2C%20y%2C%20id%3A%20randomUuid()%20%7D)%0A%20%20%20%20%20%20%20%20%20%20%20%20this.boxes.put(box)%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20box%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20addArrow(from%2C%20to)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.arrows.push(%7B%20id%3A%20randomUuid()%2C%20from%2C%20to%20%7D)%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20setSelection(selection)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.selection%20%3D%20selection%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20createBox(name%2C%20x%2C%20y%2C%20source)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20box%20%3D%20this.addBox(name%2C%20x%2C%20y)%0A%20%20%20%20%20%20%20%20%20%20%20%20this.setSelection(box)%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(source)%20this.addArrow(source.id%2C%20box.id)%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A)%0A%0A%0Aconst%20store%20%3D%20AppStore.create(%7B%0A%20%20%20%20boxes%3A%20%7B%0A%20%20%20%20%20%20%20%20%22ce9131ee-f528-4952-a012-543780c5e66d%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20%22ce9131ee-f528-4952-a012-543780c5e66d%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%22Rotterdam%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20x%3A%20100%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20y%3A%20100%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%2214194d76-aa31-45c5-a00c-104cc550430f%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20%2214194d76-aa31-45c5-a00c-104cc550430f%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%22Bratislava%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20x%3A%20650%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20y%3A%20300%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%20%20%20%20arrows%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%3A%20%227b5d33c1-5e12-4278-b1c5-e4ae05c036bd%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20from%3A%20%22ce9131ee-f528-4952-a012-543780c5e66d%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20to%3A%20%2214194d76-aa31-45c5-a00c-104cc550430f%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%2C%0A%20%20%20%20selection%3A%20null%0A%7D)%0Ainspect(store)%0A%0Aconst%20newArrow%20%3D%20store.arrows%5B0%5D.copy()%0Aconsole.log(JSON.stringify(newArrow.toJSON()))%0Aconsole.log(%22From%20X%3A%22%2C%20newArrow.from.x)%0A

**Comment by evanblack** [comment]
Thanks fro the quick response! You guys are awesome. This makes plenty of sense so thanks for the clarification. We've used Mobx on a fairly large project and just got into mobx-state-tree for things like time travel and its great. Thanks for all the work!
