### ISSUE TITLE
models with submodels

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#261]
I ask basically because it is not mentioned anywhere on the docs, but I just assumed it is correct.

can a model hold another submodel? this is

```js
const ModelA = types.model(
  'A', 
  {
    a:1
  }, {});
const ModelB = types.model(
  'B', 
  {
    b: ModelA
  }, {});
```
will that correctly serialize to ```{ b: { a: 1 } }``` ?

Also, can I do something like this to initialize ModelA to a default value inside ModelB, or do I need to use getSnapshot over the create function?
```js
const ModelB = types.model(
  'B', 
  {
    b: types.optional(ModelA, ModelA.create({})) // do I need getSnapshot here? would a plain object even work?
  }, {});
```
Or maybe it is actually the inverse and the create way is right and plain object way wouldn't even work?

Also, should I be using ```() => ModelA.create({})``` so the instance is not shared? or is it cloned for me?

**Comment by mattiamanzati** [comment]
All assertions are true, and the default value can be either a snapshot or a model instance. If a model instance is given, optional will get is snapshot and use it as default value :)

**Comment by xaviergonz** [comment]
Thanks for the answer! So then I don't really need to put create inside a lambda function because it is cloned anyway?

**Comment by xaviergonz** [comment]
Also, if I just pass {} as default value, does that mean it will auto fill in optional properties with default values for me as if I called it with create({}) ?

**Comment by mattiamanzati** [comment]
It behaves like this each time .create is called to create a new instance:
1. Is the optional parameter a function? Evaluate it each time .create is called on the model. https://github.com/mobxjs/mobx-state-tree/blob/master/src/types/utility-types/optional.ts#L45-L51
2. Is the value returned a model instance? Pick its snapshot. It's not? Ok, assume the given value is the default snapshot to use. https://github.com/mobxjs/mobx-state-tree/blob/master/src/types/utility-types/optional.ts#L29-L32

Yes, the .create work (called internally initialize because it will return an internal node instead of the actual value) is done recursively, so optionals of child models will be treated the same way! :)

**Comment by xaviergonz** [comment]
Nice! then I'll just use types.optional(WhateverModel, {})
