### ISSUE TITLE
Two types for TS Model.Type?

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#270]
Right now typeof Model.Type seems to be the "output/created" type, this is:

```js
const model = types.model('Mod',
  {
    x: 4,
    y: types.number,
  },
  {}
);

const modelInstance: typeof model.Type = {
  // cool, it complains that x is missing
  y: 6
};
```
However, is there a way to access the "create time type" used by create?

The idea is so I can do something like this:

```js
const someFunc = (instance: typeof model.CreateType) => {
  return model.create(instance);
}
someFunc({y:6}); // complains that x is missing, which should be ok
model.create({y: 6}); // this is fine and dandy
```

because if I pass {y: 6} to that function, while it would be valid it will complain that x is missing, so at the end I have to either use Partial<typeof model.Type> (which could make me miss 'y') or redeclare a custom interface and keep it in-sync with the model.

This is specially annoying when creating setters for models with submodels.

**Comment by xaviergonz** [comment]
Ah, I just noticed there's a SnapshotType! 💃 It should be on the docs :D

**Comment by xaviergonz** [comment]
Funny stuff, TS complains about this code when the setter uses SnapshotType, but not when using Type

```js
export const CharacterPortraits = types.model(
  'CharacterPortraits',
  {
    standard: Portrait,
  },
  {
    setStandard(val: typeof Portrait.SnapshotType) { 
      this.standard = val; // complains here, with plain Type it is ok
    },
  }
);
```

**Comment by mattiamanzati** [comment]
The fact is that TS assumes that the type of a property is the same of the setter, so wount allow to be both Type | SnapshotType, so we opted out for supporting just Type. SnapshotType is not documented yet because it isnt fully inferred correctly by TS right now, we are waiting for conditional types in TS :)

**Comment by mweststrate** [comment]
The latter is unavoidable with TS, it doesn't have a notion of read versus
write types. Since the read type is Type, the assignment type must be Type
as well, although MST in fact does allow the SnapshotType to be assigned.
The only way to work around that is to cast to any.

Op wo 26 jul. 2017 om 20:43 schreef xaviergonz <notifications@github.com>:

**Comment by xaviergonz** [comment]
:-/ shame, guess a typecast it is then
