### ISSUE TITLE
Introduce new syntax to declare actions and volatile state

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#282]
This issue is basically a placeholder for @mattiamanzati' s awesome idea, as demonstrated [here](https://www.typescriptlang.org/play/index.html#src=interface%20IType%3CS%2C%20T%3E%7B%0D%0A%20%20%20%20Type%3A%20T%0D%0A%20%20%20%20SnapshotType%3A%20S%0D%0A%20%20%20%20create(snapshot%3F%3A%20S)%3A%20T%0D%0A%7D%0D%0A%0D%0Ainterface%20IModelType%3CS%2C%20T%3E%20extends%20IType%3CS%2C%20T%3E%20%7B%0D%0A%20%20%20%20actions%3A%20%3CA%3E(fn%3A%20(self%3A%20T)%20%3D%3E%20A)%20%3D%3E%20IModelType%3CS%2C%20T%20%26%20A%3E%0D%0A%20%20%20%20properties%3A%20%3CP%3E(properties%3A%20%7B%20%5BK%20in%20keyof%20P%5D%3A%20IType%3Cany%2C%20P%5BK%5D%3E%20%7C%20P%5BK%5D%20%7D)%20%3D%3E%20IModelType%3CS%2C%20T%20%26%20P%3E%0D%0A%7D%0D%0Adeclare%20var%20t_number%3A%20IType%3Cnumber%2C%20number%3E%0D%0Adeclare%20var%20t_string%3A%20IType%3Cstring%2C%20string%3E%0D%0Adeclare%20var%20t_boolean%3A%20IType%3Cboolean%2C%20boolean%3E%0D%0Adeclare%20function%20model%3CP%3E(%0D%0A%20%20%20%20properties%3A%20%7B%20%5BK%20in%20keyof%20P%5D%3A%20IType%3Cany%2C%20P%5BK%5D%3E%20%7C%20P%5BK%5D%20%7D%0D%0A)%3A%20IModelType%3Cany%2C%20P%3E%0D%0A%0D%0A%2F%2F%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%20USAGE%20%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0D%0A%0D%0Aconst%20Todo%20%3D%20model(%7B%0D%0A%20%20%20%20id%3A%20t_number%2C%0D%0A%20%20%20%20name%3A%20t_string%2C%0D%0A%20%20%20%20done%3A%20t_boolean%2C%0D%0A%20%20%20%20remoteId%3A%20t_number%0D%0A%7D).actions(self%20%3D%3E%20%7B%0D%0A%20%20%20%20function%20toggle()%20%7B%0D%0A%20%20%20%20%20%20%20%20self.done%20%3D%20!self.done%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20function%20setName(name%3A%20string)%7B%0D%0A%20%20%20%20%20%20%20%20self.name%20%3D%20name%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20const%20saveToServer%20%3D%20async(self)(function*()%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20post%20to%20server...%0D%0A%20%20%20%20%20%20%20%20self.remoteId%20%3D%20yield%20fetch('http%3A%2F%2Flocalhost%2Fsample')%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20return%20%7B%20toggle%2C%20setName%2C%20saveToServer%20%7D%0D%0A%7D)%0D%0A%0D%0Aconst%20a%20%3D%20Todo.create())

Example:
```javascript
const Todo = model({
    id: t_number,
    name: t_string,
    done: t_boolean,
    remoteId: t_number
}).actions(self => {
    function toggle() {
        self.done = !self.done
    }

    function setName(name: string){
        self.name = name
    }

    const saveToServer = async(self)(function*(){
        // post to server...
        self.remoteId = yield fetch('http://localhost/sample')
    })

    return { toggle, setName, saveToServer }
})
```

**Comment by mattiamanzati** [comment]
Thanks but you made me think about that idea @mweststrate :P
The idea is that the only required piece to construct a model will be properties. Everything else will be attached at construction time.
```
interface IModelType<S, T> extends IType<S, T> {
    named: (newName: string) => IModelType<S, T>
    props: <P>(props: { [K in keyof P]: IType<any, P[K]> }) => IModelType<S, T & P>
    views: <V>(fn: (self: T) => V) => IModelType<S, T & V>
    actions: <A>(fn: (self: T) => A) => IModelType<S, T & A>
}
model(props: { [K in keyof P]: IType<any, P[K]> }): IModelType<S, P>
```
Because `name` is already a concept in MST types, we should name it either "named" (I like most) or "withName".

**overall changes:**
- now views will be separated from props, even stricter typings for model could be used, I would continue to support the "pass-in-the-default-primitive" behaviour.
- state will no longer exists. Each scope for actions will be executed at construction time. Feel free to stick in there your "state". It's even safier because you can't access it from outside. Great place to save pending promises, websocket connections, etc...
- wrapped actions will be only the exported ones. Means performance improvements, because any internal action call wont trigger isRunningActions checks.
- there is no more need to wrap view functions, because isAlive checks will be performed on properties access
- each "self => ({})" function could be considered a "construction" scope. Basically will be called at model construction time. We'll put somewere a flag to mark this construction phase, so when calling utility functions like async(self, "fetchFromServer")(.....), the async function can ensure that it's being called at construction, and not inside an action/callback.
- "no-more-this" to prevent issues with typings and different settings of noImplicitThis and things like async generator issues.

**Comment by rchanou** [comment]
@mattiamanzati Sorry to chime in, I'm not that well-versed in TS; would this be a good example in plain JS?

```js
const Todo = model({
  named: 'Todo',
  props: {
    id: t_number,
    name: t_string,
    done: t_boolean,
    remoteId: t_number
  },
  views(self) {
    return {
      shortName(length) {
        return self.name.substring(0, length);
      }
    };
  },
  actions(self) {
    // actions can be kept private/internal by *not* exporting them
    const uncheck = () => {
      self.done = false;
    };

    return {
      toggle() {
        self.done = !self.done;
      },
      setName(name) {
        uncheck();
        self.name = name;
      },
      saveToServer: async(self)(function*() {
        // post to server...
        self.remoteId = yield fetch('http://localhost/sample');
      })
    };
  }
});
```

If that's correct, I would say I would prefer that over any fluent API: it seems simpler, more flexible and less problematic (same reasons to use `flow`/`compose` over `chain` in **lodash**, or **date-fns** over **moment**).

This gets rid of `this` completely? Would there still be computed `get` properties?

I'm excited, thanks to both of you!

**Comment by mattiamanzati** [comment]
Yes, it will get rid of this completely :)
computeds can still be defined in the views section using get computed(){ return self.todos.length } for example :)
Type-wise that syntax is a little harder, so in the end its mostly a point of view :)

**Comment by mweststrate** [comment]
@rchanou the most important difference is that the fluent interface produces a fresh type on each step (all type definitions are immutable), so the type `self` in actions, refers to the type produced by the previous, `props`, `views`, etc calls

**Comment by mweststrate** [comment]
P.s. also note that without local state or private methods, actions can be simply written as:

```javascript
type.actions(self => ({
      toggle() {
        self.done = !self.done;
      },
      setName(name) {
        self.name = name;
      },
}))
```

This makes simple action blocks more easy to write :)

**Comment by tomitrescak** [comment]
Guys, looks awesome (although we just finished porting our codebase to current version of MST, more work awaits ;).

Yet, related to this, will this also simplify the Typescript model definition. It's often very difficult to read through all those type unions to see the shape of the final type. I'll probably open a new ticket, but it would be great to ditch "type" and introduce "interface", to see only the final produced type (although it still may not be possible to eliminate &'s completely)

**Comment by tomitrescak** [comment]
Yet, I wonder how will you type those private functions from the "actions" bit. But you're the magicians here ;)

**Comment by mattiamanzati** [comment]
@tomitrescak Private functions will only have "self" typed, because they are indeed private :P 
We already have a codemod I wrote that did mostly all (95%) of the job of migrating the tests codebase, would be great if before releasing the new version you could make a backup copy of your codebase and try it over the codebase to eventually address unsupported edge cases :)
You can find it here https://github.com/mobxjs/mobx-state-tree/blob/cd339acf927c6844bd11e27fda4da097fed8acc8/codemod/src/index.ts (there should be also the compiled version in the same branch)

**Comment by mattiamanzati** [comment]
No, calling .actions will produce a new type :) @dagatsoin

**Comment by caesarsol** [comment]
Great idea, this would make code more explicit, by labeling every argument block and even allow grouping actions in chunks, possibly also split in modules!

If I'm not wrong it also allows prototypal inheritance without subclassing and immutable composition, for this reason it reminds me of [stampit](https://github.com/stampit-org/stampit).

Just a couple of questions/proposals:

 - Is the interface intended to be used both with configuration object and with immutable setters?
 - Are the `views` a new concept?
 - Would you consider adding a `hooks` property for lifecycle hooks, so that they are not mixed between actions? It would be way more explicit and be less ambiguous for MST beginners, I think.

**Comment by mattiamanzati** [comment]
"Are the views a new concept?"
No, in the past computed gets and functions defined in the properties section were views, basically they can only read the state and not modify it! :)

"Would you consider adding a hooks property for lifecycle hooks, so that they are not mixed between actions? It would be way more explicit and be less ambiguous for MST beginners, I think."
Was one of my concerns. I am +1 for that, but it's hard and not fully pratical sometimes because you cannot share volatile state vars (scoped vars) between methods and lifecicles :)

I did'nt fully understood the first question :P

**Comment by caesarsol** [comment]
Ah, now I got what you mean by `views`.

About the first question, sorry for not being clear. I mean supporting both:
- `t.model({ actions: ... })` as a configuration object 
- `t.model().actions(...)` as an "immutable setter"

Could you explain better this part?
> not fully practical sometimes because you cannot share volatile state vars (scoped vars) between methods and lifecycles

Thanks!

**Comment by mattiamanzati** [comment]
The only mode supported by t.model with be with properties as argument, so properties are the only configuration object available :)

**Comment by caesarsol** [comment]
So it won't be possible to do `t.model(...).actions(...)`?

**Comment by mattiamanzati** [comment]
Sorry, I explained myself wrong, I meant that it wont be possible to do t.model({ properties: {}, actions: {}}), the t.model(arg) arg can be only the properties :)

**Comment by caesarsol** [comment]
Sorry, I understood @rchanou example was right, instead the correct one would be:

```js
const Todo = model({
  id: t_number,
  name: t_string,
  remoteId: t_number,
})
  .named('Todo')
  .props({ // Can add props separately
    done: t_boolean,
  })
  .views(self => ({
    shortName(length) {
      return self.name.substring(0, length)
    },
  }))
  .actions(self => {
    const uncheck = () => {
      self.done = false
    }

    return {
      toggle() {
        self.done = !self.done
      },
      setName(name) {
        uncheck()
        self.name = name
      },
      saveToServer: async(self)(function * () {
        self.remoteId = yield fetch('http://localhost/sample')
      }),
    }
  })
```

Is this right?

**Comment by mattiamanzati** [comment]
Exactly! :)

**Comment by mattiamanzati** [comment]
released with 0.10!

**Comment by ticruz38** [comment]
One of the thing I liked with the old implementation was to be able to define some properties in the volatile state, use them in my react view, but not getting them in the snapshot generated by getSnapshot. Would that be possible with the new syntax?

**Comment by mattiamanzati** [comment]
Please see #456 which is moving forward that direction :)
