### ISSUE TITLE
Usage with classes?

### ISSUE THREAD

**Issue by natew** [mobxjs/mobx-state-tree#3]
Just curious if this is planned/possible?

**Comment by mattiamanzati** [comment]
I think that the "problem" would be handling constructor parameters.
Maybe the "createFactory" signature could change and accept something like "createFactory(environment => objectLike)" to enable DI.
Not tested, but think that right now you can use something like createFactory(new MyClass()).

**Comment by ConneXNL** [comment]
I agree it would be really nice if we can use exisiting mobx classes with the state tree.

**Comment by mweststrate** [comment]
The reason why I would like to to avoid that is that classes make deserialization hard, and they introduce many edge cases to support; statics, enumerables, inherited fields, properties, inheritance, etc etc. It would make it really hard to support all these cases in in all api's. So for now my intention is to *not* support classes, a constraint which allows for many generic solutions.

**Comment by zgover** [comment]
@mweststrate Is this something we may evaluate and reconsider? At a minimum, provide a limited usage when used in classes (e.g., exclude overrides/subclassing similarly to MobX contingencies, etc), released in parallel with a new `experiments` configuration object to opt into unstable features. No need to worry about covering every edge case until the community can advise. 

Since this was closed, numerous improvements and changes have been made across all related technologies/languages. Specifically, a few to mention, Microsoft has deployed the typescript release v3.7 which provides support for a new configuration option [`useDefineForClassFields`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier). This may provide at least inspiration for a solution potentially resolving your reservations from before when this issue was created/closed. Additionally, new decorators standard + TSv5 adoption of it. Lastly, for further type safety the new `overrides` `satisfies` and more...

[<img width="1012" alt="image" src="https://user-images.githubusercontent.com/9044773/230751703-49d6381a-502f-43ac-863e-41e1c632654e.png">](https://www.typescriptlang.org/tsconfig#useDefineForClassFields)

This is the sole reason I am not adopting MST in any implementations of MobX, regardless of the number of benefits or the value it may provide. This is due to TS classes being strictly and immutably defined in most project scope requirements.
