### ISSUE TITLE
using in ionic2 application?

### ISSUE THREAD

**Issue by aaronksaunders** [mobxjs/mobx-state-tree#320]
_My apologies if this should be a stackoverflow question._

was trying to use mobx-state-tree in a ionic2 angular2 application.

getting weird type errors in the stackblitz.com example I have here - https://ionic-mobx-mobx-state-tree.stackblitz.io in file `todoStoreMST.ts`
```
Supplied parameters do not match any signature of call target.
```

when I export to ionic2 cli havent figured how to address type error either.

**Comment by mattiamanzati** [comment]
Can you please copy here the source code? From my browser I see no errors opening that example :)

**Comment by aaronksaunders** [comment]
![screen shot 2017-08-21 at 12 30 32 pm](https://user-images.githubusercontent.com/524953/29529362-5dae0c10-866d-11e7-88ad-699b6850a258.png)

source code is here...

https://github.com/aaronksaunders/ionic2-mobx-state-tree/blob/master/src/todoStoreMST.js

**Comment by mattiamanzati** [comment]
Oh, Thats a known limitation of TS!
Thats because MST allows to read model properties as one type (e.g. ObservableArray) but to set as two possible type (e.g. ObservableArray or an array of snapshots) and thats unsupported in TS. Due to this limitation, we have chosen to read and set as the real type (e.g. ObservableArray).
Since you are using snapshots, you can avoid that by using applySnapshot(self.todos, self.todos.filteelr....) or skip typechecks by casting "as any" your value! :)
Feel free to close the issue if everything is ok :)
