### ISSUE TITLE
detach is broken in 0.10

### ISSUE THREAD

**Issue by evanblack** [mobxjs/mobx-state-tree#335]
I'm not having any luck detaching nodes within arrays in v0.10. It tells me the array is protected.

I've created 2 sandboxes - 
v0.9.5: https://codesandbox.io/s/8llyk16729
v0.10.2: https://codesandbox.io/s/yrx2yxr6j

Works in 0.9.5, but not in 0.10. I even tried to add a `detachNode` action for the `Page`, but I think the protection issue is on the array, not the `Page` model.

**Comment by mattiamanzati** [comment]
Ok, found out the issue.
https://github.com/mobxjs/mobx-state-tree/commit/5feec3bd7740abea4ade570e1bf22be276b805cd#diff-8406aeda76dceeb1a83b0a0392bba4ecL76
In 0.10 node are'nt marked "in-action" from root anymore, instead the "context" (a.k.a. the node that owns the function) is.
In the example, the action is called on the child node, so the child is marked as "running an action", while the parent is'nt. So when detach performs the remove on the parent array, it fails because it has'nt been marked as "running an action". This behaviour would also throw if you try to modify a node which belongs to the same tree, but on a different branch.
I see correctness and potential in this behaviour, but possible breakish :/
@mweststrate We could ideally add a runInContext for the detach/destroy methods to ensure that also the parent would enter in action phase, but we should allow that only if a current action is running, otherwise it will break time travelling.

**Comment by theankurkedia** [comment]
Not only detach, but destroy is also showing the same error, I worked around it by creating that action in the parent and accessing that node using the index. Then it works fine.

**Comment by mattiamanzati** [comment]
@theankurkedia Yep, that's basically the gist. In older version action scope were initialized at root, now at the node owning the action. Imho we could keep this behaviour, but need to discuss with @mweststrate :)

**Comment by evanblack** [comment]
Thanks for looking at this!

Yeah, it's not just the `parent`, but the action needs to be on the `root` node. That's the only way I can get it to work (other than `unprotect`), which seems less than ideal to me. The more deeply nested the data, the further down you have to drill from the root (i.e. `self.chapters[ci].pages.splice(pi, 0, p)`)

Working example:
https://codesandbox.io/s/pky61pl66m

**Comment by evanblack** [comment]
Scratch that. I guess the `detach` is all that needs to live at the root. So adding a utility action that just detaches at the root store is sufficient.

**Comment by abruzzihraig** [comment]
@evanblack @mattiamanzati It won't hurt like that. See https://codesandbox.io/s/r0ymkoy37o, we can simply wrap the function `detach` to an action of root or parent of which node we want to modify.

**Comment by abruzzihraig** [comment]
Furthermore, I got another similar situation based on that new 'protect' strategy:
```
        duplicate() {
            const copy = smartClone(self);

            const container = getParent(self, 2);
            const idx = container.findObjectIndex(self);

            container.setObject(copy, idx + 1);
        }
```
Here you can see I use two methods `findObjectIndex` and `setObject` from the parent of the current instance instead of modifying the `container` directly in that child's `duplicate` action.
