### ISSUE TITLE
Custom error message for typecheck 

### ISSUE THREAD

**Issue by the-noob** [mobxjs/mobx-state-tree#364]
It would be nice to be able to supply custom messages for `typecheck` errors

```JavaScript
const TaskStore = types
    .model('TaskStore', {
        status: {types.string, 'Status has to be string'},
        name: {types.refinement(types.string, value => value.length > 5), 'Min length 5'}
    })
```
Or is it more appropriate to have a pre-validator on the stuff you're passing to `create`?

```JavaScript
const validator = (entity) {
  const errors = [];
  if (entity.name.length < 5) {
    errors.name = 'Min length 5';
  }
  return errors;
}

if (validator(input)) { TaskStore.create(input) } 
```
This is a bit annoying because you'll end up duplicating validation logic...

**Comment by mattiamanzati** [comment]
At the moment is some sort of "internal" API, but you could use Type.validate(value) that returns an array of object with the invalid path and eventually the reason for the field being invalid.

**Comment by jayarjo** [comment]
IIs it possible to simply intercept validation error that might occur during `Type.create()`?

**Comment by mweststrate** [comment]
just wrap a function around it?

function createCar(snapshot) {
   if (!Car.validate(snapshot))
      throw "dude, where is my car?"
   return Car.create(snapshot)
}

Op za 3 mrt. 2018 om 16:30 schreef Davit Barbakadze <
notifications@github.com>:

**Comment by jayarjo** [comment]
@mweststrate thanks for the hint. I went and actually tried to wrap `Type.create()` in `try...catch` and it seems to intercept the error nicely. I'm not sure what's the current situation around using `try...catch` (I bet it's a new evil), but seems fine for my needs.

**Comment by mweststrate** [comment]
try catch is fine, the only trick with try catch is that it might trigger
other errors (for example, you have valid snapshot, but a typo in a
afterCreate action. You probably don't want to catch those and report them
back as 'invalid json', because that isn't the case (In Java you could
nicely specify catch handlers only for specific errors, but here you have
to write some manual code to 'recognize' the correct exception)

Op za 3 mrt. 2018 om 20:06 schreef Davit Barbakadze <
notifications@github.com>:
