### ISSUE TITLE
Looking for some guidance perhaps...?

### ISSUE THREAD

**Issue by jole78** [mobxjs/mobx-state-tree#516]
I'm looking into modeling a backend domain model i MST and having some issues understanding how to support creating a new instance of my MST model.

Say that my model has an identifier (a database pk on the back-end which is a number) and it also has another field that is supposes to be unique. It looks something like this:

```
export const Incident = types
    .model("Incident", {
        id: types.identifier(types.number),
        registration_number: types.string,
        belongs_to: types.reference(Organisation)
    })
```
So, this basically says that an incident has to have an id, a registration number and it has to belong to an organisation.

But say that some user wants to create a new incident. Then it doesn't have any of these fields set before the user picks an organisation and then fills out some other data and persists the incident.
That's how it works on the back-end at least (python django), where I can create an instance of an incident (and instance of the class Incident) but it doesn't get an id or a reference number until I persist it (basically when I call save).

Does MST support this or am I totally misunderstanding the usage of MST here.

btw, loving all the work going into MST...it looks very very promising.

**Comment by jiyinyiyong** [comment]
Does this help? https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#typesoptional

**Comment by luisherranz** [comment]
You need to give it a client identifier when you create the instance. That can be anything, for example, a random or incremental number, and it shouldn't change. You can save your backend identifier on another prop.

```javascript
export const Incident = types
    .model("Incident", {
        id: types.identifier(types.number),
        backendId: types.maybe(types.number),
        registration_number: types.mabye(types.string),
        belongs_to: types.reference(Organisation)
    })
```

**Comment by d4rky-pl** [comment]
Consider using `uuid`s instead of incremental PKs. Or at least keep them next to incremental PK to be able to generate unique keys on your client side, for example [with uuid library from npm](https://www.npmjs.com/package/uuid) :)

**Comment by jole78** [comment]
Thanks for all the comments but I feel I need to extend my feedback on MST. Please please note that this isn't a rant on MST or anything...it's just some feedback and possibly some misunderstandings that I feel is needed on MST documentation/examples?? maybe also to help others.

1. I thought that MST was a way for me to express my domain model in javascript (on the client) as way for me to move from a "classic" MVC server stack (like python django or asp.net mvc or what not). Most server stacks that support domain models (or models in general) have the ability to create an instance of the model and then before persisting it you can enforce validation. On field types, if that is not already in the language like it is on asp.net, and on validation rules. If validation passes it then gets persisted and thus will have an identifier assigned. MST doesn't support this since all validation on field types happens when I create the model. From my point of view this forces me to express my model's identifier twice...one identifier that's purely for integrity (like keys in react) and one for the external id...which can't be set as required (have to use types.maybe). If this is indeed the desired outcome wouldn't MST benefit from handling all that identity stuff internally instead??
Validation could perhaps be opt-in when it occurs...so I as a developer could control it.

2. The examples I see of MST always "load" the complete model state (from a remote location...usually a json file acting like a database) upon startup. Most applications I've developed doesn't use that approach at all. Probably they start by authenticating the user (thus perhaps creating an instance of a user model) and sticking that on the store or on a <Provider /> component. Maybe the user also belongs to an organisation (also an MST model), thus it has a reference to said organisation.

Later on the user creates an incident (which also has a reference to an organisation). 
`const incident = Incident.create({belongs_to: props.user.belongs_to}) `
Perhaps like that??

A little later the user wants to list their incidents...(calling the server api)...if I then want to create incidents from the snapshots the server returned I would get an error that one of the organisations already belongs to (well the same organisation as the user ---> user.belongs_to).
Wouldn't MST benefit from being a little "smarter" here perhaps. Like it would know that "ok, that organisation that you're referencing there...I already have that so I'm re-using it for you".
At least that's how libraries like apollo-client (graphql) handles these situations.

3. Things that do work really great are snapshots, patches, type "safety". And overall I think MST is great library but maybe it needs either some clarifications or some improvements/guidance.

**Comment by mweststrate** [comment]
Hey @jole78,

Thanks for your feedback! The library is still young and most things are planned to be addressed in the near feature (this year hopefully). Of some problems we were aware, but nonetheless left them open until we have more insight in the actual needs. (For example, there is much less need for custom types as I expected, and much more for custom references) Some of them you can already find addressed in open issues. But here a short overview of plans we have.

1. The issue of domain identifiers versus MST identifiers (`types.identifer()`) is one we hear quite regularly. Probably we need to relax the constraints and make it possible to not set identifiers yet. THis means we need to make the reconciler a little bit more relaxed, as it will now use identifiers to do reconcilation. This is probably the hardest of the problems.

2. Loading after the facts is mostly due to the example models being to simple. Creating a type like `children: types.maybe(types.array(Child))` and a `load()` action should generally address this. We do plan on creating a `types.lazy(types.array(Child))` that lazily children when needed, although this won't fit all use cases. 

3. For references we will soon introduce support for custom setters  + getters. Where the getter is also allowed to return a promise. This makes it possible to load in additional data as well when trying to resolve a promise

Didn't exactly get the incident problem, but when `identifiers()` are used, mst will reuse instances.

Thanks for the feedback!

**Comment by mweststrate** [comment]
@jole78 the 1 issue can now be solved much more elegantly, as references can since 1.2 be defined with custom resolve logic, which makes it possible to not just use `types.identifier()`, but arbitrary fields as foreign keys (and even load that data on demand).

Hope that helps!

Closing issue as other questions are also reflected partially in other open issue, but thanks again for the extensive feedback
