### ISSUE TITLE
[Bug] When I change model's two props in flow, trigger render() two times 

### ISSUE THREAD

**Issue by zhangjunah** [mobxjs/mobx-state-tree#563]
When I change a model's two props in  async action by `flow` , and the two lines code without any `yield `, but the render method still triggerd two time.  This is the same problem as  https://github.com/mobxjs/mobx-state-tree/issues/519 , but three days has passed, and that issue is closed, so I create this issue.

And I create codesandbox: https://codesandbox.io/s/oqkzjm9wmy

when you click the 'load data' button, the console show like this:

![1](https://user-images.githubusercontent.com/1746154/33985882-caa83780-e0f6-11e7-82e5-f4233dae3d5a.png)

my model is like this:

![2](https://user-images.githubusercontent.com/1746154/33985886-d07e5522-e0f6-11e7-855d-4df1cc5f8650.png)

**Comment by tinchoz49** [comment]
Hi @zhangjunah! yeah, yesterday I report the same problem on the gitter channel, because I'm having  performance issues since every mutation in each async actions is recomputing all the related computations.

I don't know if this is the expected behaviour for the async actions. The asyncAction from mobx-utils seems to be working as we expected, the last block is wrapped in a single action. https://github.com/mobxjs/mobx-utils#asyncaction
 
What you can do for now is move your last two mutations to a different action.

**Comment by mweststrate** [comment]
Confirmed, will investigate!

**Comment by mweststrate** [comment]
Fixed in 1.3.1, thanks for the detailed reproduction @zhangjunah
