### ISSUE TITLE
[Feature Request] allow `types.model()` to accept instance of complex model type

### ISSUE THREAD

**Issue by hackape** [mobxjs/mobx-state-tree#564]
**Do you want to request a *feature* or report a *bug*?**  

Feature.

**What is the current behavior?**
```
const ParentNodeModel = types.model({
  childNode1: childNodeInstance1,
  childNode2: childNodeInstance2,
  ...,
})
```
Above usage gets runtime error:
```
[mobx-state-tree] In property 'childNode1': base model's should not contain complex values: 'AnonymousModel@<root>'
```

whereas the legit (yet tedious) usage goes:
```
const ParentNodeModel = types.model({
  childNode1: types.optional(ChildNodeModel1, childNodeInstance1),
  childNode2: types.optional(ChildNodeModel2, childNodeInstance2),
  ...,
})
```

**What is the expected behavior?**

It's a very common pattern to declare the subtree node models separately, then assemble them in containing folder's `index.ts` then send them up layer by layer, until we got a the global root tree node. 

Thus I do believe it'll be a useful pattern to allow the aforementioned usage. It shouldn't be hard to implement, since `ChildNodeModel` is in fact accessible at `childNodeInstance.$treenode.type`.

**Which versions of mobx-state-tree are affected by this issue?**
v1.2.1

**Comment by wprater** [comment]
I recently overcame this issue using `volatile` state.

**Comment by mweststrate** [comment]
@hackape so you mean that the above example should translate to 

```javascript
const ParentNodeModel = types.model({
  childNode1: getType(childNodeInstance1),
  childNode2: getType(childNodeInstance2),
})
```

 it is not hard to implement potentially, but won't this be confusing, as you are using an *instance* in a *type* position? That means that just the shape of the instance is take and it's type is inferred. However, that means that when creating a new instance of `ParentModel` these fields still needs to be provided, which can be fixed by using the following pattern:

```javascript
const ParentNodeModel = types.model({
  childNode1: types.optional(getType(childNodeInstance1), childNodeInstance1),
  childNode2: types.optional(getType(childNodeInstance2), childNodeInstance2)
})
```

That works as expected, however I am not entirely fond of it.
1. I think the difference between using an instance in a type position is quickly confusing
2. This might not work entirely as you expect. When creating a `ParentNodeModel`, `optional` will actually _clone_ the default value. In other words, `ParentNodeModel.create().childNode1 !== childNodeInstance1`. (the reason for that is that it would otherwise be impossible to ever create a second `ParentNodeModel`, as `childNodeInstance1 ` could not become it's child anymore, as it already has a parent). 

So although syntax-wise this is quite convenient, I fear that it might result in subtle semantics that might not be picked up by the reader of your code, so I'm not sure this is a good idea. Will leave it open for a while to see what others think

**Comment by robinfehr** [comment]
i kind of like the approach of using the prototype pattern here to assemble them though I think having an "api sugar" would be better than omitting the types completely - type inferring should be indicated. 

maybe something like `fromPrototype` in its name that would also indicate the 2. point you mentioned @mweststrate.

**Comment by robinfehr** [comment]
as discussed with @mweststrate this is a won't fix for now - I personally liked it but for now it does not suit because:

- currently we don't store types within mst itself and we currently should focus on bringing down the memory before storing more
- a helper function is implementable by the users using `getMembers` to achieve that.

**Comment by hackape** [comment]
sorry i totally missed out the discussion here. i agree with choosing explicity over convenience on this one. and yes, currently i am using api sugar util like @robinfehr suggested to get around tedium. thanks for your attention guys.
