### ISSUE TITLE
Not understanding Mobx concept

### ISSUE THREAD

**Issue by lan-nguyen91** [mobxjs/mobx-state-tree#647]
Could some help explaining how `views` tight to the `store`, and if I need to use snapshot in MST  for the case below:

I have `Todo` model, and `Todos` store
```
const Todo = types.model("Todo", {
    selected: false,
}).actions(self => {
    let toggleSelect = (bool) => self.selected = bool;
    return { toggleSelect };
});
```
```
const Store = types.model("Store", {
    todos: types.array(Todo),
})
.views(self => {
     return {
	 get selectedTodos() {self.instances.filter(instance => instance.selected)};
     };
})
```

I pass props to list view like, **Main.js**
``` 
@inject('TodoStore')
@obsever
//// code ////
componentWillRecieveProps() { console.log('new props');}
//// code ////
<CheckboxList
    open={this.state.openList}
    todo_store={todo_store}
    ****selectedTodos={todo_store.selectedTodos}****
/>
```

And controller code, **CheckboxList.js**
```
//---  List Code --- //
props.todo_store.todos.map(todo => {
   return <Toggle toggled={todo.selected}  onToggle={(, bool) => todo.toggleSelect(bool) }/>
}
//---  List Code Cont --- //
```

My question is ***selectedTodos={todo_store.selectedTodos}***, if I have this then the checkbox is checkable and `new props` string always printed, 
if not then the checkbox doesn't perform any interaction and no console.log. 

Why do I need to subscribe to a view in order to get the state updated, shouldn't the state of the store still update accordingly.

Ui looks like this 
![image](https://user-images.githubusercontent.com/14827876/36004330-07f3a36a-0ce7-11e8-95ce-14c9ca432db5.png)

Thanks

**Comment by mweststrate** [comment]
The problem is probably that your list component is not an observer. The main component should *not* be reacting normally when you toggle the items. Why; because it doesn't need to. The childs could rerender them selves without the parent. 

By subscribing to the filtered items you cause the main compoonent to (unnecessarily) rerender when the set of filtered items changes. But as a side effect it will cause its own child to rerender (because that one is not an observer now, so the default behavior to React is to forcefully re-render all children). So the effect of that is that the UI suddenly appears interactive. But you achieved it in the wrong way; by re-rendering the whole component tree. 

If you add observer to your List component you will see that in that case your main component will stop rerendering, and List will take care of that itself. 

btw, make sure to use a key in your `Toggle` components.

**Comment by lan-nguyen91** [comment]
awesome explanation, thanks that's clear things up alot. 👍
