### ISSUE TITLE
Redux perks parity

### ISSUE THREAD

**Issue by janat08** [mobxjs/mobx-state-tree#650]
[Perks list](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367)
The above link mentions perks that justify the use of redux, with minimal code changes how many of these mobx state tree matches.

**Comment by robinfehr** [comment]
it comes with all of these (as far as I've understood them from quickly reading over the list) and a bit more fine grained control because of patches.
would take a bit too long to show you an example of them all but I'm sure by getting into MST you'll find out about all of them.

as a start you could for example watch this egghead course:
https://egghead.io/courses/manage-application-state-with-mobx-state-tree

many of the mentioned points of the article are already covered there.

**Comment by janat08** [comment]
Maybe this belongs in the docs touching on the comparison?

**Comment by janat08** [comment]
As in supposedly, it will compete.

**Comment by robinfehr** [comment]
docs can be improved for sure. 
one day we might see a similar article with the headline `You might not need MST`
such could be linked for sure.

**Comment by janat08** [comment]
It may even read: We're garbage use redux for the same perks,  and more

**Comment by mattruby** [comment]
@janat08 PRs are welcome.
