### ISSUE TITLE
How to properly create models tree with unique id per model type?

### ISSUE THREAD

**Issue by optimatex** [mobxjs/mobx-state-tree#677]
First of all, I'd like to mention that I'm happily using mobX in my app for 2 years and now I'd like to migrate to MST. 
From the docs, I got that it's super important that each identifier of certain models type was unique per models tree. Does it mean, that I have to build my models tree only with normalizer, similar as in redux apps? 
For example, I have a UserStore, and the app may contain UserStore in 4 places simultaneously: in the header, in the user page, in the user list that follow me, modal selector, and in the sidebar with offered users. The only way I see how to design a tree model with a single store id per tree is next:
```
app: { 
  users: {
    data: {    // Here we store something like a database
      1: { name: 'alex', age: 41 },
      2: { name: 'tom', age: 42 }
    },
    userScene: 1, // Id of the user that is currently showed 
    list: [1,2,3], // Ids of the list from main content scention, followers in our case
    selectList: [11,12,13], // the list of users which are showed in modal selector
    authUser: 2, // logined user, showed in header 
  } 
}
```
and next we user views to get users from `data` prop (our client database).

Is there some other way, how to achieve the same goal but without normalizer process? 

In my previous app, all models were organized as a graph. That has some problems with updating all showed users in the app, when someone edits username, for ex. However, But it was much easier to update each store and all data flows was more straightforward

**Comment by lishine** [comment]
In your solution you actually use the data in denormalized way. For example selectList[0].name

**Comment by optimatex** [comment]
@lishine Thanks for the response. But why this example is denormalized? 
I have each model as a singleton in my tree and use references instead of duplication of same models. I might be wrong, but these examples were described in https://github.com/paularmstrong/normalizr and some Redux tutorials

**Comment by lishine** [comment]
You define selectList as array of references to the users from data. And then selectList[0] returns you the user itself. This is how mst works - look at the documentation, it is the magic. 
You a can still access in a normalized way: data[select[0]]

**Comment by optimatex** [comment]
@lishine Thanks. I read docs and watch all @mweststrate videos\courses multiple times. But perhaps, this part is not clear to me. For example, what happened if I will use the app for a while and my app.users.data will contain hundreds of thousands of users? It may need to clear this "client storage", but in that case, we may encounter a situation when some ref will be pointing to deleted model. There is an error in this case,  but for me, it's not obvious how to avoid this

**Comment by lishine** [comment]
The obvious is to check that reference resolves, using some mst api like isAlive, or maybe there is something specific to resolving references. Maybe there are better solutions...

**Comment by lishine** [comment]
I wish we had some mobx-state-tree channel to talk

**Comment by optimatex** [comment]
@lishine there is this https://gitter.im/mobxjs/mobx-state-tree. However, it is a common channel with a discussion of any part of lib.

**Comment by lishine** [comment]
Thanks

**Comment by mweststrate** [comment]
Closing for now, question seems answered

**Comment by nachiket-p** [comment]
@optimatex Did you find the answer to your question. I am shifting from Redux, Selector & Normalizr to mobx + MST. I have the same question. Does MST take care of normalization or we have to maintain manually?

**Comment by duro** [comment]
This is also a confusion for me. Based on what I am seeing in the `mst-example-bookshop` example, it would seem that the best practice is the same as Redux. Have root level "collections" for each entity type. In my case and "Offer" has a reference to a "Location". When I query our API for offers, the Location associated with each offer comes down denormalized (e.g location is embeded into offer).

Would I still need to use normalizr to pick these apart and store them into their respective collections? Where is the best place to store the action that adds them to those collection maps.

So far, this is where I am headed:

```
const RootStore = types.model({
  session: types.optional(Session, {}),
  offers: types.optional(OffersCollection, {
    entities: {}
  }),
  locations: types.optional(LocationsCollection, {
    entities: {}
  })
})

export const OfferModel = types.model({
  _id: types.identifier(types.string),
  title: types.string,
  location: types.reference(LocationModel)
})

export const OffersCollection = types.model({
  entities: types.map(OfferModel)
})

export const LocationModel = types.model({
  _id: types.identifier(types.string)
})

export const LocationsCollection = types.model({
  entities: types.map(LocationModel)
})
```

BUt I have no idea is I am making more work for myself, or doing this totally wrong?

**Comment by ashconnell** [comment]
I'm running into issues related to this too.

My store is generally split into 2 categories:

1. Model storage: eg `store.books = types.model('Book', {...})`
2. Query references: eg `store.currentBook = types.reference(Book)`, `store.bookSearchResults = types.array(types.reference(Book))`

This is a pretty clean way to structure a store. It keeps everything flat for root level access to everything, but allows the query references to be entry points into a cyclical tree.

In order to support this our API returns data normalized for easy insertion, for example searching books returns 

```json
{
  response: [...BookID],
  entities: {
    book: [...Book],
    author: [...Author]
  }
}
```

Since our store snapshots are persisted (react-native w/ offline support) the data continues to grow without any way to remove models (1) that aren't referenced in any active queries (2).

There are a few things that would make this less painful:

**Model Cleanup**
Being able to call something like `removeUnreferenced(store.books)` that removes all models that aren't referenced anywhere else in the tree. This would make persistence perfectly devoid of stale data.

**Tree Insertions**
Being able to insert into a reference eg `store.bookSearchResults = nestedApiResponseOfBooksWithAuthors` and have it automatically upsert the models into the model storage. This would remove the need to normalize manually.

My biggest issue right now is the snapshot continuing to grow.
