### ISSUE TITLE
Need better error message: cannot read property 'instantiate' of undefined

### ISSUE THREAD

**Issue by chenyong** [mobxjs/mobx-state-tree#682]
![image](https://user-images.githubusercontent.com/25790987/36881554-aa2e1f10-1e09-11e8-8817-64a9cbcf823b.png)

I know it's because typecheck failed. But can we get a better error message here. Best solution to me is to turn it into a warning. What do you think?

**Comment by robinfehr** [comment]
can you elaborate why a warning?

**Comment by robinfehr** [comment]
i guess you're doing something like - can currently not imagine another way to reproduce your problem.
```js
const User = types.model({ 
  name: types.late(() => undefined) // should be types.undefined instead
})   
```
mst needs types returned when using `types.late` and can (atm) not infer from default values (e.g. 'someString' => types.string)

**Comment by chenyong** [comment]
No, I looked into the problem in development mode, it's just normal error when data loaded from server   does not match definitions in the model. It's not a bug in MST, but a design decision that made us frequently break our program.

**Comment by robinfehr** [comment]
i see you're in production mode :) there is: [typecheck](https://github.com/mobxjs/mobx-state-tree/blob/master/API.md#typecheck) that might help you check your values before applying in prod mode.

just using a warning seems not really possible since the types are used to generate consistent snapshots. if there suddenly would be a value stored that couldn't be serialized anymore according to the types `getSnapshot()` implementation, the snapshot model - declared through types on a model - wouldn't be correct anymore.

**Comment by chenyong** [comment]
Understood. I know `typecheck` and it's used in some of the code. What do you suggest in our case?

**Comment by robinfehr** [comment]
hard to tell without knowing more about the code base. 
but for sure your model does not yet match the data you fetch and try to put in.

you might wan't to consider using `types.union` / `types.maybe` / `types.optional`
and loosen your model. 

if you have completely different structures - maybe `types.frozen` could help out

if you have inconstant data that needs to be  cleaned up - you might wan't to tangle the problem differently and try to catch the errors `typecheck` provides and try to resolve the problem with some logic.
 
e.g. on gitter - the community can for sure help if you'd present the use case. think that would unnec. blow up the issue here.

**Comment by nitzantomer** [comment]
I agree with the OP, the error message needs to change, it currently has no meaningful name/information.

My problem was that I defined properties as `types.string` while the updating snapshot contained numbers.  
It took me a while to understand what the problem was, but if the error would have hinted to the right direction it could have been great.

**Comment by mweststrate** [comment]
Nitzan, if you cannot trust the data you receive, run the Type.is(..)
first! We cannot get really useful errors without running the typechecker

Op di 26 jun. 2018 om 14:54 schreef Nitzan Tomer <notifications@github.com>:
