### ISSUE TITLE
tryResolve does not work as advertised

### ISSUE THREAD

**Issue by RobiFerentz** [mobxjs/mobx-state-tree#686]
I have a model with a reference to another model where not all ids can be resolved to an actual instance of the referenced model.

Firstly, I would expect a reference under types.maybe() to fail silently should it fail to reconcile an identifier to an actual instance, but that is just my opinion.

Be that as it may, I have tried using tryResolve in order to avoid throwing an exception, and while it definitely succeeds when an identifier is reconciled; when it is not, it still throws the same error as when trying to access the reference property directly, thus completely missing the point of tryResolve according to documentation.

**Comment by robinfehr** [comment]
also the `resolve` does not exist anymore (README)

**Comment by dnakov** [comment]
related to #668

**Comment by mweststrate** [comment]
@RobiFerentz could you provide an example test case?

**Comment by mslenc** [comment]
@mweststrate I can, because I just hit the same problem:

[Code](https://mattiamanzati.github.io/mobx-state-tree-playground/#src=import%20%7B%20tryResolve%2C%20getSnapshot%2C%20types%2C%20isStateTreeNode%20%7D%20from%20%22mobx-state-tree%22%0Aimport%20%7B%20observer%20%7D%20from%20%22mobx-react%22%0A%0Alet%20id%20%3D%201%3B%0A%0Aconst%20Foo%20%3D%20types.model('Foo'%2C%20%7B%0A%20%20%20%20id%3A%20types.identifier()%2C%0A%20%20%20%20name%3A%20types.string%0A%7D)%3B%0A%0Aconst%20Bar%20%3D%20types.model('Bar'%2C%20%7B%0A%20%20%20%20mimi%3A%20types.string%2C%0A%20%20%20%20fooRef%3A%20types.reference(Foo)%0A%7D)%3B%0A%0Aconst%20Root%20%3D%20types.model('Root'%2C%20%7B%0A%20%20%20%20foos%3A%20types.map(Foo)%2C%0A%20%20%20%20bar%3A%20Bar%0A%7D)%3B%0A%0Aconst%20root%20%3D%20Root.create(%7B%0A%20%20%20%20foos%3A%20%7B%20%7D%2C%0A%20%20%20%20bar%3A%20%7B%0A%20%20%20%20%20%20%20%20mimi%3A%20'mimi'%2C%0A%20%20%20%20%20%20%20%20fooRef%3A%20'123'%0A%20%20%20%20%7D%0A%7D)%3B%0A%0A%2F%2F%20Error%3A%20%5Bmobx-state-tree%5D%20Failed%20to%20resolve%20reference%20of%20type%20Foo%3A%20'123'%20(in%3A%20%2Fbar%2FfooRef)%0Alet%20noMimi%20%3D%20tryResolve(root%2C%20'%2Fbar%2FfooRef')%3B%20%0A%0A%2F%2FError%3A%20%5Bmobx-state-tree%5D%20No%20child%20'name'%20available%20in%20type%3A%20reference(Foo)%0Alet%20noName%20%3D%20tryResolve(root%2C%20'%2Fbar%2FfooRef%2Fname')%3B%20%0A%0Aconsole.log(noMimi)%3B)

**Comment by mweststrate** [comment]
@mslenc, thanks! added PR to address: #692
