### ISSUE TITLE
Has Many Relationships

### ISSUE THREAD

**Issue by mjewell** [mobxjs/mobx-state-tree#714]
Is it possible to look up a reference in reverse? Would be cool if we could model 1:n relationships the same way databases do, where we find all things that have a reference to a node, like this:

```js
const BookStore = types.model("Store", {
  id: types.identifier()
});

const Book = types.model("Book", {
  store: types.reference(BookStore, { inverseOf: 'books' }) // something like this?
});

const bookStore = BookStore.create({ id: '1' });
const book1 = Book.create({ store: bookStore });
const book2 = Book.create({ store: bookStore });
const book3 = Book.create({ store: bookStore });

console.log(store.books); // [book1, book2, book3]
```

**Comment by robinfehr** [comment]
no - you'd need to add an array/ map of books to your store to achieve that. 
the types / models are used to create a serialised state and should represent such.

the problems of such magic property: 
- one could easily run into bugs overwriting them accidentally. 
- instances could already be created of one model before the magic property would be added. that would lead to inconsistent nodes.

that works for relational databases because the tables/relationships are declaratively setup before you do CRUD operations. MST does not enforce such setup upfront and does therefore not work like that.

**Comment by mjewell** [comment]
Hmm, you could definitely implement this as a computed field

**Comment by mjewell** [comment]
Sorry didn't mean to close.

You could implement this yourself as a computed property which grabbed all the instances of Book and filtered them when they have a reference to you. Wouldn't that solve those problems? Not sure if that's really possible to implement just through some property on the reference on the Book side though

**Comment by robinfehr** [comment]
`grabbed all the instances of Book`

when you create a new node using `.create()` MST does not store the the node on the type.
therefore you'd still have to maintain a separate collection to store all the nodes/instances to filter them. you can either store them on the tree e.g. adding an array like i did mention above or you can store them in a separate array. the tree option has the advantage that you're actually able to serialise them using `getSnapshot()`
