### ISSUE TITLE
applySnapshot replaces the same array field members

### ISSUE THREAD

**Issue by morr** [mobxjs/mobx-state-tree#799]
Code:

```javascript
import { types, onPatch, applySnapshot } from 'mobx-state-tree';

const X = types
  .model('X', {
    id: types.identifier(types.number),
    name: types.string
  });

const Z = types
  .model('Z', {
    name: types.string,
    xs: types.array(X)
  });

const z = Z.create({ name: 'z1', xs: [{ id: 1, name: '1' }, { id: 2, name: '2' }] });

onPatch(z, (patch) => {
  console.log(patch);
});

applySnapshot(z, {
  name: 'z2',
  xs: [{ id: 1, name: '1' }, { id: 2, name: '2' }]
});
```

What I expect to see in console:
```javascript
{op: "replace", path: "/name", value: "z2"}
```

What I actually see in console:
```javascript
{op: "replace", path: "/name", value: "z2"}
{op: "remove", path: "/xs/1"}
{op: "remove", path: "/xs/0"}
{op: "add", path: "/xs/0", value: {…}}
{op: "add", path: "/xs/1", value: {…}}
```

Is it expected behaviour or bug?

**Comment by omerman** [comment]
It is expected. If you want only a a patch event to occur, you should use `applyPatch`.

* Not that I tried this, but Im guessing you could `preProcessSnapshot` for Z(you can make the pre processor generic, so you can apply it on every other store).
The pre processor could prevent replacing values with the same values.. and will make the `applySnapshot` fire the patch events that actually changes your data values.

**Comment by morr** [comment]
@omerman ok. thanks.

**Comment by omerman** [comment]
@morr 
I misguided you, `preProcessSnapshot` won't do what I suggested it could..
Use `applyPatch` instead of `applySnapshot` and it will surely do the trick..

**Comment by carlosagsmendes** [comment]
@morr did you find a solution for this? I need to get a snapshot from the model, let a user edit it, and apply it back on save, and then send the patches to other users since it's a real-time collaborative editing scenario. Thanks in advance

**Comment by morr** [comment]
@carlosagsmendes can't remember it now, but I think I switched from `applySnapshot` to `applyPatch`.

**Comment by ConneXNL** [comment]
Isn't this just a bug?

**Comment by BrianHung** [comment]
```
{op: "remove", path: "/xs/1"}
{op: "remove", path: "/xs/0"}
{op: "add", path: "/xs/0", value: {…}}
{op: "add", path: "/xs/1", value: {…}}
```

There are two things that cause these extra patches.
1. `onPatch` doesn't respect transaction boundaries, so patches are emitted as objects are changed. This means they are _not_ compressed at the end of the transaction when `onSnapshot` is called. To compress patches, using the [immer trick which does a diff](https://github.com/mobxjs/mobx-state-tree/discussions/1976#discussioncomment-6610371).
2. Re-applying redundant patches (doesn't actually change state) will cause those patches to be re-emitted. This is because during the reconciliation process, [only `Object.identity` is used for comparison](https://github.com/mobxjs/mobx-state-tree/blob/94bb7d02de6ed3e2c3f92a6a6ddadc16644597f0/packages/mobx-state-tree/src/core/node/object-node.ts#L530) instead of a deep equals.
