### ISSUE TITLE
Error "The object has died, it cannot be used anymore" occures in unmounted components.

### ISSUE THREAD

**Issue by elite174** [mobxjs/mobx-state-tree#800]
I made an example with reproduction of the error. Please, help me how to avoid it.
P.S. I can't use createPortal because of some reasons.

Example: https://codesandbox.io/s/6wn4781y6n

**Comment by omerman** [comment]
First of all, I believe you should observe the App component instead of Row.. This will surely solve your case. if you observe the App, once you clear the `store.arr` the App will re-render causing Row to have the right & up to date props.

So why is this happening?

The Row observer causes a re-render whenever the element is changed since you read it's content.

When the element is destroyed(after clearing the array), the Row observer re-renders, in that case you attempt to access the element values.. and since the element is no longer on the MST tree(the array is cleared and does not contain the item) you get the error "The object has died, it cannot be used anymore"

Hope this helps:

https://codesandbox.io/s/7zl36vo6mx

**Comment by elite174** [comment]
But then the component looses the ability to be reactive. Try my updated example.

https://codesandbox.io/s/0qnxr29qp0

**Comment by omerman** [comment]
https://codesandbox.io/s/531qmpqvnn
Above is kinda better practice.. where you have the App component that passes the data required by Row.

If you look at the console, App would re-render, and pass the right props to Row.
The reason Row isn't reactive at the example, is because you are mounting Row under some other DOM element and you prevent updates on `willReceiveProps`...

**If you insist on Row being the observer**, pass an id or index in your case to it, and get the values from `store.arr` using an index, if the index doesnt exist, handle it correctly.. this way you will not get "object died..." exception..
see this: https://codesandbox.io/s/lrrozm95p7

**Comment by elite174** [comment]
The point is that inside the modal there are components that more complicated than Row. I know that it's better to use componentWillMount etc. however, if I wanted to use them, I would use redux. I insist that mobx-state-tree shouldn't trigger unmounted components' render functions.

**Comment by mweststrate** [comment]
Closing as question seems answered
