### ISSUE TITLE
types.identifier should only accept strings (and drop `()`)

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#807]
Fixes quite some issues and makes the model more uniform, for example #792. Refining identifers could be done using `types.refinement(types.identifier, i => ...)`

**Comment by mweststrate** [comment]
probably it should accept number still as well, but should be refined with `refinement(identifier, string)` rather than `identifier(string)`

**Comment by luisherranz** [comment]
Is it a good idea to automatically turn numbers into strings inside `identifier`?

Things like:
```js
applySnapshot(self, [{
  id: 1, // valid, but transformed into string
  data: 'text 1',
}, {
  id: 2, // valid, but transformed into string
  data: 'text 2',
}]);

self.someMap.set(
  1, // valid, but transformed into string
  { data: 'text' }
);
```

I ask this because usually ids are stored using numbers in APIs and a common pattern on MST is to use that API json to create a new item. Having to manually transform all your ids seems cumbersome.

We also could apply the same principle to the getters:
```js
self.someMap.get(1); // valid, but transformed into string
```

**Comment by mweststrate** [comment]
See #904. MST 3 will introduces `types.identifier` and `types.identifierNumber`. This will result in always consistent identifier types in snapshots and at runtime. Only for map keys / lookups they will be normalized to string (as objects cannot have numeric indices)
