### ISSUE TITLE
Error 'Type alias 'IStore'  circularly references itself' when used inside generator function

### ISSUE THREAD

**Issue by abubberman** [mobxjs/mobx-state-tree#823]
HI,

I have an issue using the type of a store inside an async action (Generator syntax using flow).

![image](https://user-images.githubusercontent.com/13328911/40165478-6195679c-59bc-11e8-8aa1-ef16bf8d5eba.png)

I can suppress the error using // @ts-ignore, but the interface is not recognized anymore, so no intellisense or type checking anymore.

![image](https://user-images.githubusercontent.com/13328911/40165531-8e4f33e4-59bc-11e8-95a2-591fedb49612.png)

is there a solution for this issue?

Many thanks

**Comment by fruitraccoon** [comment]
I tried to reproduce this error myself and couldn't get quite the same one (Got _"[ts] 'myActionName' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer."_ instead).

But the way I handle it is to capture the `root` instance as [volatile-state](https://github.com/mobxjs/mobx-state-tree#volatile-state). For example:

```
.actions(self => {
    const root = getRoot(self) as IRootStore;

    const createAsset = flow(function*(command: CreateCommand) {
      yield root.item.createItem(command);
    });
})
```

**Comment by abubberman** [comment]
That does not seem to work for me. I still get the same error. 

otherStore.ts
![image](https://user-images.githubusercontent.com/13328911/40475334-a28550f2-5f41-11e8-818a-5f0a237a373e.png)

rootstore.ts
![image](https://user-images.githubusercontent.com/13328911/40475282-7e6bb6c0-5f41-11e8-805e-175a062ca3ed.png)

When I use the following code, the error is gone, but the type information is also gone:
![image](https://user-images.githubusercontent.com/13328911/40475693-75866662-5f42-11e8-97f7-66099513e927.png)


I Also, I have another issue  that is related to this one: [https://github.com/mobxjs/mobx-state-tree/issues/824](url). When using 2 yield statements in a  generator function, the following error occurs:

>  'Cannot modify 'Store', the object is protected and can only be modified by using an action'

So at this moment, i'm forced to use promise.then().

**Comment by fruitraccoon** [comment]
I think the difference is in the way that `IRootStore` is declared.  Rather than

```
export type IRootStore = typeof Root.Type;
```
I use something like
```
type RootStoreType = typeof Root.Type;
export interface IRootStore extends RootStoreType {}
```
([approach described here](https://github.com/mobxjs/mobx-state-tree#using-a-mst-type-at-design-time)).  As TypeScript treats interfaces differently to type aliases, I think it makes all the difference.  Worth a try?

Regarding the 2nd issue, I haven't run into that - I can't find the exact situation that's described in the issue in my code though, so possibly it'll pop up sometime.  I'd think using `.then` would be fine unless you were really needing to have middleware get involved between the calls.

**Comment by abubberman** [comment]
I still get the same error. It seems to be the combination with the flow statement.
The issue with the flow statement is caused by a wrong import. I had imported flow from 'mobx' instead of' 'mobx-state-tree'

**Comment by mweststrate** [comment]
Note: if the circular dependency is not caused by the type definition, but by an action or view, this problem is circumventable by specifiying explicit return types, see for example the `stores.js` in https://codesandbox.io/s/rjl5m8jyqm versus https://codesandbox.io/s/0p2pw3xzqp 

```typescript
onst WorkplaceProviderStore = types
  .model("WorkplaceProviderStore", {})
  .actions(self => {
    const fetch = flow(function*(url: string) {
      return yield getRoot<Instance<typeof RootStore>>(self).fetchSingle(
        "<url>"
      );
    });

    // circular dep because return type of fetch depends on RootStore, 
    // but RootStore's type depends WorkPlaceProviderStore
    return { fetch };
  });

export const RootStore = types
  .model("RootStore", {
    work: types.optional(types.late(() => WorkplaceProviderStore), { info: {} })
  })
```

But the following signature of fetch break the circular type dependency because the return type 
of fetch no longer depends on the type of `RootStore`. Obviously you can put any other type than `any` there, as long as it is not `RootStore` or WorkplaceProviderStore` itself :-). 

```typescript
  .actions(self => {
    
    const fetch = flow(function*(url: string): /* type annotation */ any {
      return yield getRoot<Instance<typeof RootStore>>(self).fetchSingle(
        "<url>"
      );
    });
```

**Comment by abubberman** [comment]
Thanks for this response. This also works in my situation! 
I only had to add the return type to the function and the error is gone.

In the meantime, I also found a workaround to get rid of the circular depencency, but the solution above is a lot better.

``` javascript
// My solution

const loadPlanning = flow(function*() {
    var rootStore = getRoot(self) as IRootStore;
    var token = yield rootStore.authenticationStore.aquireTokenForApiCall();
    self.planningList = yield activiteitenApi.fetchPlanningForActiviteitAsync(token, self.id );
    });

const loadPlanningAsync = () => {
      return loadPlanning();
    };

return { loadPlanningAsync };
```
``` javascript
// Current code

const loadPlanning = flow(function*():  any {
    var rootStore = getRoot(self) as IRootStore;
    var token = yield rootStore.authenticationStore.aquireTokenForApiCall();
    self.planningList = yield activiteitenApi.fetchPlanningForActiviteitAsync(token, self.id );
    });

return { loadPlanning};
```

**Comment by mweststrate** [comment]
Hah `activiteitenApi`, you're 🇳🇱/🇧🇪?

Op wo 29 aug. 2018 09:14 schreef abubberman <notifications@github.com>:

**Comment by abubberman** [comment]
Yeah NL :-)

**Comment by SaebAmini** [comment]
@mweststrate's workaround worked perfectly for me too. Had to explicitly specify the generator function's return type, which was `IterableIterator<Promise<void>>` in my case. e.g.

```
const foo = flow(function*(): IterableIterator<Promise<void>> {
  yield root.bar();
  yield baz();
});
```

**Comment by elie222** [comment]
Also worked for me. I think it could be useful to add this information to the Typescript section of the README.
