### ISSUE TITLE
Models with no required fields should implicitly be optional

### ISSUE THREAD

**Issue by pelotom** [mobxjs/mobx-state-tree#831]
A common pattern I am seeing in my code is, e.g.

```ts
const ParentModel = types
  .model({
    child1: types.optional(ChildModel1, {}),
    child2: types.optional(ChildModel2, {}),
    child3: types.optional(ChildModel3, {}),
  })
```

it would be nice if this could simply be expressed as

```ts
const ParentModel = types
  .model({
    child1: ChildModel1,
    child2: ChildModel2,
    child3: ChildModel3,
  })
```

**Comment by kgwebsites** [comment]
The same argument could be made the other way if it were types.required instead of types.optional. I believe the reason types.required is implicit as opposed to types.optional, is to give a more stable structure of your model by default so that you know for a fact that a model will have specific data and then you specify the items which could be optional. It's all opinionated.

The second example you provided could easily still be achieved like so:

`
const ChildModel1 = types.optional(types.model('ChildModel1', {
  ...
}), {});
const ChildModel2 = types.optional(types.model('ChildModel2', {
  ...
}), {});
const ChildModel3 = types.optional(types.model('ChildModel3', {
  ...
}), {});
const ParentModel = types
  .model({
    child1: ChildModel1,
    child2: ChildModel2,
    child3: ChildModel3,
  })
`

**Comment by mweststrate** [comment]
Implicitly using `{}` would create harder error messages; as `{ child2: something, child3: something }` would give a validation error on the first required attribute of `ChildModel1`, instead on the root object that lacks a `child1` field. `{}` is not an acceptable default for a lot of objects. 

But you can always define your own utilities to fix that:

```
const c = modelType => types.optional(modelType, {})

const ParentModel = types
  .model({
    child1: c(ChildModel1),
    child2: c(ChildModel2),
    child3: c(ChildModel3),
  })
```
