### ISSUE TITLE
introduce utility methods?

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#84]
currently only computed values and actions can be defined on a model. However utility method (that can be tracked, unlike actions) or static methods now need to be defined outside models. Find a place for them inside models?

**Comment by mweststrate** [comment]
To elaborate on this one:

```javascript
const Store = types.model({
   todos: types.array(Todo),
   get completedTodos() { return this.todos.filter }, // OK -> computed
   addTodo(todo) { this.todos.add(todo) }, // OK -> action
   searchTodos(text) { // Not ok, will become an actionwhich is tracked
      return this.todos.filter(t => t.title.indexOf(text) !== -1)
   }
})
```

Solutions:

1. Introduce `util`
`searchTodos: util(function (text) { })`

2. Or restore explicit actions again
`addTodo: action(...)`

3. Or define actions on models seperately
or to create action, pass a second argument to `types.model` which defines all the actions?

What dou you think @mattruby @raineratspirit?

**Comment by mattiamanzati** [comment]
@mwestrate I like mostly the third one, would also allow clearer typings because we can make the first parameter accept only factories and immutable values, and the second actions. About static ones, imho they are not needed. They can be wrote as functions with object as first parameter. And do we really want untracked ones in models?

**Comment by mweststrate** [comment]
Me too, so that changes the example to: 

```javascript
const Store = types.model({
   todos: types.array(Todo),
   get completedTodos() { return this.todos.filter }, // OK -> computed
   searchTodos(text) { // OK -> a view. Not allowed to have side effects
      return this.todos.filter(t => t.title.indexOf(text) !== -1)
   }
}, {
   addTodo(todo) { this.todos.add(todo) }, // OK -> action
   // hooks also go in here
})
```

**Comment by RainerAtSpirit** [comment]
Version 3 looks good to me.

**Comment by mweststrate** [comment]
Eh problem with that, the `this` for actions is hard to type. 

An alternative could be:

```
const Store = types.model({
   todos: types.array(Todo),
   get completedTodos() { return this.todos.filter }, // OK -> computed
   searchTodos(text) { // OK -> a view. Not allowed to have side effects
      return this.todos.filter(t => t.title.indexOf(text) !== -1)
   }
}, (instance) => {

   function addTodo(todo) { 
      instance.todos.add(todo)
   }

   return { addTodo }
})
```

but that get's quite verbose. Small upside is that this introduces a 'postCreate' for free :)

**Comment by mattiamanzati** [comment]
@mweststrate have you checked out ThisType of TS2.3? https://github.com/Microsoft/TypeScript/pull/14141

**Comment by mweststrate** [comment]
Freaking genious :)

**Comment by mattruby** [comment]
I'm digging this implementation. Post create is really useful.

**Comment by mattiamanzati** [comment]
@mattruby @mweststrate yeah, lifecycle events are awesome. Looking forward to preprocessSnapshot and postprocessSnapshot :P

**Comment by mweststrate** [comment]
@mattiamanzati specific use cases already?

**Comment by mweststrate** [comment]
`ThisType` is genious btw. Really solves this issue

**Comment by mattiamanzati** [comment]
@mweststrate mostly to polyfill missing array of references, and because I have some rest api built up with Laravel (PHP Framework) which includes snapshots also for related data (e.g. Comment author, category data, etc...). In my store that data is normalized, so I would like to do creation of missing entities at /entities/[name]/[id] directly on the snapshot logic instead of preprocessing the snapshot and then apply it :)

**Comment by mweststrate** [comment]
@mattiamanzati can you open seperate issue?
