### ISSUE TITLE
map.put throws error, works fine with map.set(id, value)  

### ISSUE THREAD

**Issue by jonavila** [mobxjs/mobx-state-tree#876]
I'm getting the following error when using `put` to add to a map. 
`Cannot add an object to a state tree if it is already part of the same or another state tree. Tried to assign an object to '<somepath>', but it lives already at '<anotherpath>'`

This seems to be the same issue described in #383.
I was able to reproduce in CodeSandbox and it seems to only happen if I use `preProcessSnapshot`. The problem doesn't occur if i use `map.set(id, value)`

Here's a link to the sandbox showing the error.

https://codesandbox.io/s/ox6v8jrl9y

Reference line 36 of alertStore.js

**Comment by k-g-a** [comment]
Good day! 
I nailed down the problem. 
The obviuos part was in map's put method: when ```mapType.identifierMode === MapIdentifierMode.UNKNOWN``` we first create model and then move it to proper place via setParent during reconcilation. But all the mess comes from ```preProcessSnapshot``` and it was a little bit harder to find out why. So here's step by step explanation of what's going on:
- everythings goes well until we call ```self.alerts.put(alert);``` at ```AlertStore.afterCreate().load()```;
- ```put()``` falls down to path with ```MapIdentifierMode.UNKNOWN``` and executes ```const node = getStateTreeNode(mapType.subType.create(value))```
- at this point the whole tree with initialValues is craeted;
- next, at ```put()``` we call ```this.set("" + node.value[node.identifierAttribute], node.value);``` with the previously crated tree (node);
- this ```set``` is intercepted by ```MapType.willChange()```, we go through "add" codepath (as there is still no values in our map, it was created standalone) and fall to ```change.newValue = this.subType.instantiate(node, key, undefined, change.newValue);```
- subtype is ```ModelType``` and at it's ```instantiate``` we call ```createNode()```, but pass ```this.applySnapshotPreProcessor(snapshot)``` as ```initialValue``` argument;
- because of ```applySnapshotPreProcessor``` in previous step ```isStateTreeNode(initialValue)``` at ```createNode``` fails (```initialValue``` is plain object once again) and instead of just calling ```setParent()``` it goes wrong: new ObjectNode is craeted, it's childen are instantiated, ```events``` array tries to reconcile and everything falls apart.

If we remove ```preprocessSnapshot``` from AlertModel - everything goes well as initialValue is not spoiled.

It seems that we can add check to ```ModelType.instantiate``` whether ```initialValue``` is plain object or node and skip ```applySnapshotPreProcessor``` for the latter.
