### ISSUE TITLE
How to detect that the snapshot was applied?

### ISSUE THREAD

**Issue by khomyakov42** [mobxjs/mobx-state-tree#881]

**Comment by mweststrate** [comment]
It is applied if no exception was thrown.

**Comment by khomyakov42** [comment]
I mean the action in the life cycle

**Comment by mweststrate** [comment]
Sorry, the previous answer was trying be as vague as the original question
to hint the question asked was below par :). Please formulate issues
clearly, with a small code example / use case and expected / needed /
observed behavior

Op ma 18 jun. 2018 om 09:20 schreef Sergey Khomyakov <
notifications@github.com>:

**Comment by khomyakov42** [comment]
when I take a snapshot of the data may not be downloaded from the server. After applying the snapshot, I would like to resume loading the data if necessary. I could use something like afterApplySnapshot for this.
```javascript
const Product = types.model('Product', {
  id: types.identifier(),
  name: types.string,
});


const SelectedProduct = types.model('SelectedProduct', {
  id: types.maybe(types.number),
  product: types.maybe(Product),
}).actions(self => ({
   load: flow(function* load(productId) {
  	self.id = productId;
        const response = yield fetch(`/products/${productId}`);
        const data = yield response.json();
        self.product = data;
  }),
  
  afterApplySnapshot() {
  	if (self.id != null && self.product == null) {
    	self.load(self.id).catch(e => logger.exception(e));
    }
  }
}));

```

**Comment by mweststrate** [comment]
There is no such hook, and there seems no intermediate need: you can just call `self.afterApplySnapshot()` after the `self.product =` assignment. 

In general it should not matter _how_ an object was updated for your logic (otherwise you will be increasing coupling). So in principle it should not matter whether an object was changed with a snapshot, or by doing some assignments yourself.
