### ISSUE TITLE
extend should support chaining actions if they are defined multiple times

### ISSUE THREAD

**Issue by mweststrate** [mobxjs/mobx-state-tree#96]
...somehow. What should be the behavior? Sounds a lot like mixins...

**Comment by mattiamanzati** [comment]
What about something like
const Base = t.model({ hello(){ console.log('hello'); })
 extend(Base, super => ({ hello(){ super.hello(); console.log('its me');})) ?

We could also change t.model to accept a function returning the model def instead of the model def. (that would also solve some problems with circular references, but would require to refactor object to create the model def returning function on create.

**Comment by mattiamanzati** [comment]
const Base = t.model( super => ({ hello(){ console.log('hello'); })) // super is an empty object if no parent, or null
const Foo = t.model(super => ({ hello(){ super.hello(); console.log('its me');})) 

const Bar = extend(Base, Foo) // Foo will be called with Bar definition as super

**Comment by mattiamanzati** [comment]
Already addressed. Using compose you can call the parent method by using `ParentModel.actions.methodName.apply(this, ...args)`
