### ISSUE TITLE
model extendClass and extendDecorate idea

### ISSUE THREAD

**Issue by xaviergonz** [mobxjs/mobx-state-tree#982]
I have:

* [x] Feature request
   * [x] Describe the feature and why you feel your feature needs to be generically solved inside MST
   * [x] Are you willing to (attempt) a PR?
   
What about a extendClass model method that works like this?
```ts
    const M = types.model({ x: 5 }).extendClass(self => {
        class E {
            @modelState
            localState = 3

            @modelView
            get x2() {
                return self.x * 2
            }

            @modelView
            xBy(by: number) {
                return self.x * by
            }

            @modelAction
            setX(x: number) {
                self.x = x
            }

            @modelAction
            setXBy(x: number) {
                this.setX(this.xBy(x))
            }

            @modelAction
            setLocalState(x: number) {
                this.localState = x
            }
        }
        return E
    })
```

**pros:**
- basically this allows interactions between views/actions/state in an easier way
- doesn't break any compatibility, since it is a new method
- might make typings faster since it uses a class?
- PR ready :D

**cons:**
- classes need to have given a name (TS doesn't support (yet?) decorators inside anonymous classes), so this won't work
```ts
.extendClass(self => (
  class {
    ...
  })
)
```
- bound methods give problems since they bind to the class instance (which is not self)
  - non arrow function methods get bound to self properly though

**future:**
- if TS ever adds decorator support for any object properties then a similar extendObject method could be created (like extendDecorate but with actual decorators)

**Comment by Bnaya** [comment]
It would also improve the performance of server!

**Comment by xaviergonz** [comment]
how come?

**Comment by Bnaya** [comment]
read https://github.com/mobxjs/mobx-state-tree/issues/705#issuecomment-385341525 and comments afterward

**Comment by xaviergonz** [comment]
would the decorate version help as well?

**Comment by xaviergonz** [comment]
PR for extendDecorate there as well, I think I prefer that one because while uglier it doesn't allow the programmer to make as many mistakes

**Comment by xaviergonz** [comment]
@Bnaya  I just read the thread. I think that while extendClass might help with the actions/views/state it wouldn't help with the props part

Either way I think that both (extendClass and extendDecorate) would make types a tiny bit faster since:
a) usually only use one of these would be used for each model
b) rather than an union of actions & views & state it just uses the whole object interface

**Comment by xaviergonz** [comment]
That being said, maybe the props part typing could be speed up by using something like
model(new Props({ x: 5; ... })) ?

**Comment by mweststrate** [comment]
@xaviergonz  Sorry, again, for the late response. 

I would try to stay away from using classes, because in my experience (mobx) it opens an endless request for feature requests, because if class syntax is supported, one expects also al things that comes with classes to [be supported](https://github.com/mobxjs/mobx-state-tree/issues/3#issuecomment-259057305). Things like `instanceof`, `extends`, `static`, `super`, constructor, decorators (not just the ones provided by MST), and decorator setup is still an issue for many. All of those features have to work (or needs explanation again again why they don't work)

The second option feels like it is not to far from the current [`.extend`](https://github.com/mobxjs/mobx-state-tree#volatile-state) options, and serving the same goal? (except that fields are grouped per type rather then decorated

Did you see https://github.com/mobxjs/mobx-state-tree/issues/893 by @mattiamanzati ? It is quite similar to extend, except that the the type definitions are first. I do see quite some merit in that solution for two reasons:
1) it simplifies the typing and type inference of model types (especially own type function arguments etc are easy to type)
2) the solution could actually internally generate a class and yield a lot of performance benefits from that. Not necessarily, but it is a possibility. (Downside: no bound `self`, but context sensitive `this` instead)

**Comment by xaviergonz** [comment]
@mweststrate no problem about the late response :)

I was afraid of what you mention exactly about classes after writing extendClass (for example, what would happen with undecorated properties?), that's why I thought then of extendDecorate

About extendDecorate, yes, basically it is like the current extends, but the decoration approach allows an easier way to have inter-dependencies between actions/views/state

For example, in a first version of a model I had I wrote something like this
```
.views(self => {
  const views = {
    get view1() { ... },
    get view2() { uses views.view1},
    get view3() { uses views.view2},
  }
  return views
})
```

and it was working, but what I didn't realize at first is that the cached value of view1 was never used when using view2, and same with view3, so after realizing that I had to do:
```
.views(self => ({
  get view1() {...}
}))
.views(self => ({
  get view2() { uses self.view1}
}))
.views(self => ({
  get view3() { uses self.view2}
}))
```
which gets old quickly and gets even more exacerbated when you have to remember to keep the order right (dependent views below), so the idea is that with extendsDecorate it would end up as
```
.extendDecorate(self => ({
  get view1() {},
  get view2() { uses this.view1 },
  get view3() { uses this.view2 }
}), {
  view1: "view",
  view2: "view",
  view3: "view",
})
```
where the declaration of view1/2/3 could be even out of order, it wouldn't matter

I must confess I did not read #893 before, I will write comments on it there

**Comment by xaviergonz** [comment]
ah, also another reason was that having a single type interjection is faster than having many for TS

**Comment by xaviergonz** [comment]
Guess I'll close this and the PRs now that TS type completion got faster and "this" can be safely used inside views/actions (and it is not like views will ever use actions, so :) )
